# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mousewheeld.v1 import calibration_pb2 as mousewheeld_dot_v1_dot_calibration__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mousewheeld/v1/calibration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalibrationStub:
    """Counts per centimetre, and how it was measured.

    **This daemon owns the calibration.** The firmware knows counts and nothing
    else; vstimd is told centimetres and restates nothing; triald needs
    centimetres too and cannot read either one's config. One copy, here, and
    every number that leaves is in centimetres.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadCalibration = channel.unary_unary(
                '/mousewheeld.v1.Calibration/ReadCalibration',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.ReadCalibrationRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.CalibrationState.FromString,
                _registered_method=True)
        self.ReplaceCalibration = channel.unary_unary(
                '/mousewheeld.v1.Calibration/ReplaceCalibration',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.CalibrationPatch.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.CalibrationState.FromString,
                _registered_method=True)
        self.ReadBall = channel.unary_unary(
                '/mousewheeld.v1.Calibration/ReadBall',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.ReadBallRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.FromString,
                _registered_method=True)
        self.ReplaceBall = channel.unary_unary(
                '/mousewheeld.v1.Calibration/ReplaceBall',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.FromString,
                _registered_method=True)
        self.StartMeasuring = channel.unary_unary(
                '/mousewheeld.v1.Calibration/StartMeasuring',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.StartMeasurement.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.MeasurementStarted.FromString,
                _registered_method=True)
        self.FinishMeasuring = channel.unary_unary(
                '/mousewheeld.v1.Calibration/FinishMeasuring',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.FinishMeasuringRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.MeasurementResult.FromString,
                _registered_method=True)
        self.ApplyMeasurement = channel.unary_unary(
                '/mousewheeld.v1.Calibration/ApplyMeasurement',
                request_serializer=mousewheeld_dot_v1_dot_calibration__pb2.ApplyMeasurementRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.MeasurementApplied.FromString,
                _registered_method=True)


class CalibrationServicer:
    """Counts per centimetre, and how it was measured.

    **This daemon owns the calibration.** The firmware knows counts and nothing
    else; vstimd is told centimetres and restates nothing; triald needs
    centimetres too and cannot read either one's config. One copy, here, and
    every number that leaves is in centimetres.
    """

    def ReadCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceCalibration(self, request, context):
        """Change one or more axes. Absent fields are left alone, so a panel may send
        a single number. An axis name the rig does not have is a 404, never a new
        axis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBall(self, request, context):
        """The 2-D ball. Answers 501 until the hardware exists — declared so that
        adding it is filling in rather than redesigning.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceBall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMeasuring(self, request, context):
        """Begin counting for a guided measurement.

        **The measurement is the point.** `counts_per_rev / (π · diameter_cm)`
        describes a wheel the animal does not run on: what a corridor position is
        made of is how far the feet travelled, on the surface they touch, with
        whatever tread is on it — a few percent off the nominal every time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishMeasuring(self, request, context):
        """Stop counting and report what the wheel said, beside what the config says.
        Nothing is changed by this call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyMeasurement(self, request, context):
        """Apply the last measurement.

        A separate, deliberate press, because a calibration change invalidates
        every compiled zone set: a set armed under one calibration is never
        silently reinterpreted under another.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalibrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadCalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCalibration,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.ReadCalibrationRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.CalibrationState.SerializeToString,
            ),
            'ReplaceCalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceCalibration,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.CalibrationPatch.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.CalibrationState.SerializeToString,
            ),
            'ReadBall': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBall,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.ReadBallRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.SerializeToString,
            ),
            'ReplaceBall': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceBall,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.SerializeToString,
            ),
            'StartMeasuring': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMeasuring,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.StartMeasurement.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.MeasurementStarted.SerializeToString,
            ),
            'FinishMeasuring': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishMeasuring,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.FinishMeasuringRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.MeasurementResult.SerializeToString,
            ),
            'ApplyMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyMeasurement,
                    request_deserializer=mousewheeld_dot_v1_dot_calibration__pb2.ApplyMeasurementRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_calibration__pb2.MeasurementApplied.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mousewheeld.v1.Calibration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mousewheeld.v1.Calibration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calibration:
    """Counts per centimetre, and how it was measured.

    **This daemon owns the calibration.** The firmware knows counts and nothing
    else; vstimd is told centimetres and restates nothing; triald needs
    centimetres too and cannot read either one's config. One copy, here, and
    every number that leaves is in centimetres.
    """

    @staticmethod
    def ReadCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/ReadCalibration',
            mousewheeld_dot_v1_dot_calibration__pb2.ReadCalibrationRequest.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.CalibrationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/ReplaceCalibration',
            mousewheeld_dot_v1_dot_calibration__pb2.CalibrationPatch.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.CalibrationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/ReadBall',
            mousewheeld_dot_v1_dot_calibration__pb2.ReadBallRequest.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceBall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/ReplaceBall',
            mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.BallCalibration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMeasuring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/StartMeasuring',
            mousewheeld_dot_v1_dot_calibration__pb2.StartMeasurement.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.MeasurementStarted.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishMeasuring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/FinishMeasuring',
            mousewheeld_dot_v1_dot_calibration__pb2.FinishMeasuringRequest.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.MeasurementResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Calibration/ApplyMeasurement',
            mousewheeld_dot_v1_dot_calibration__pb2.ApplyMeasurementRequest.SerializeToString,
            mousewheeld_dot_v1_dot_calibration__pb2.MeasurementApplied.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
