# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mousewheeld.v1 import config_pb2 as mousewheeld_dot_v1_dot_config__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mousewheeld/v1/config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigStub:
    """Rates, and the line map.

    **Two kinds of setting, and the split is deliberate.** The wiring — which
    pin is `zone_goal`, which port the board is on — is changed where wiring is
    described, in the rig config file, and is not writable over this API. The
    rates are changed per session, by a person at a console, and are.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadConfig = channel.unary_unary(
                '/mousewheeld.v1.Config/ReadConfig',
                request_serializer=mousewheeld_dot_v1_dot_config__pb2.ReadConfigRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_config__pb2.ConfigView.FromString,
                _registered_method=True)
        self.PatchConfig = channel.unary_unary(
                '/mousewheeld.v1.Config/PatchConfig',
                request_serializer=mousewheeld_dot_v1_dot_config__pb2.ConfigPatch.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_config__pb2.ConfigView.FromString,
                _registered_method=True)
        self.ReadLines = channel.unary_unary(
                '/mousewheeld.v1.Config/ReadLines',
                request_serializer=mousewheeld_dot_v1_dot_config__pb2.ReadLinesRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_config__pb2.LineMap.FromString,
                _registered_method=True)


class ConfigServicer:
    """Rates, and the line map.

    **Two kinds of setting, and the split is deliberate.** The wiring — which
    pin is `zone_goal`, which port the board is on — is changed where wiring is
    described, in the rig config file, and is not writable over this API. The
    rates are changed per session, by a person at a console, and are.
    """

    def ReadConfig(self, request, context):
        """The settings a session may change and the ones it may only read, in one
        answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchConfig(self, request, context):
        """Change the rates. Absent fields are left alone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLines(self, request, context):
        """The output lines, by name.

        Read-only over the API: a zone set says `"line": "zone_goal"`, and the pin
        behind that name belongs to the rig's config. This is the same split
        statemachined draws between its graphs and its line map.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadConfig,
                    request_deserializer=mousewheeld_dot_v1_dot_config__pb2.ReadConfigRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_config__pb2.ConfigView.SerializeToString,
            ),
            'PatchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchConfig,
                    request_deserializer=mousewheeld_dot_v1_dot_config__pb2.ConfigPatch.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_config__pb2.ConfigView.SerializeToString,
            ),
            'ReadLines': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLines,
                    request_deserializer=mousewheeld_dot_v1_dot_config__pb2.ReadLinesRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_config__pb2.LineMap.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mousewheeld.v1.Config', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mousewheeld.v1.Config', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Config:
    """Rates, and the line map.

    **Two kinds of setting, and the split is deliberate.** The wiring — which
    pin is `zone_goal`, which port the board is on — is changed where wiring is
    described, in the rig config file, and is not writable over this API. The
    rates are changed per session, by a person at a console, and are.
    """

    @staticmethod
    def ReadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Config/ReadConfig',
            mousewheeld_dot_v1_dot_config__pb2.ReadConfigRequest.SerializeToString,
            mousewheeld_dot_v1_dot_config__pb2.ConfigView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Config/PatchConfig',
            mousewheeld_dot_v1_dot_config__pb2.ConfigPatch.SerializeToString,
            mousewheeld_dot_v1_dot_config__pb2.ConfigView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadLines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Config/ReadLines',
            mousewheeld_dot_v1_dot_config__pb2.ReadLinesRequest.SerializeToString,
            mousewheeld_dot_v1_dot_config__pb2.LineMap.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
