# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mousewheeld/v1/config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mousewheeld/v1/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmousewheeld/v1/config.proto\x12\x0emousewheeld.v1\"\xa2\x02\n\nConfigView\x12\x18\n\x07rate_hz\x18\x01 \x01(\rR\x07rate_hz\x12\x1e\n\ndisplay_hz\x18\x02 \x01(\rR\ndisplay_hz\x12\"\n\x0cring_minutes\x18\x03 \x01(\rR\x0cring_minutes\x12\x1a\n\x08shm_name\x18\x04 \x01(\tR\x08shm_name\x12\x1a\n\x08shm_open\x18\x05 \x01(\x08R\x08shm_open\x12\x1e\n\nshm_writes\x18\x06 \x01(\x04R\nshm_writes\x12\x1e\n\nevent_port\x18\x07 \x01(\rR\nevent_port\x12\x0c\n\x04port\x18\x08 \x01(\t\x12\x30\n\x13starves_the_display\x18\t \x01(\x08R\x13starves_the_display\"\xa6\x01\n\x0b\x43onfigPatch\x12\x1d\n\x07rate_hz\x18\x01 \x01(\rH\x00R\x07rate_hz\x88\x01\x01\x12#\n\ndisplay_hz\x18\x02 \x01(\rH\x01R\ndisplay_hz\x88\x01\x01\x12\'\n\x0cring_minutes\x18\x03 \x01(\rH\x02R\x0cring_minutes\x88\x01\x01\x42\n\n\x08_rate_hzB\r\n\x0b_display_hzB\x0f\n\r_ring_minutes\"4\n\x07LineMap\x12)\n\x05lines\x18\x01 \x03(\x0b\x32\x1a.mousewheeld.v1.OutputLine\"T\n\nOutputLine\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0b\n\x03pin\x18\x03 \x01(\r\x12\x1c\n\tsafe_high\x18\x04 \x01(\x08R\tsafe_high\"\x13\n\x11ReadConfigRequest\"\x12\n\x10ReadLinesRequest2\xe5\x01\n\x06\x43onfig\x12K\n\nReadConfig\x12!.mousewheeld.v1.ReadConfigRequest\x1a\x1a.mousewheeld.v1.ConfigView\x12\x46\n\x0bPatchConfig\x12\x1b.mousewheeld.v1.ConfigPatch\x1a\x1a.mousewheeld.v1.ConfigView\x12\x46\n\tReadLines\x12 .mousewheeld.v1.ReadLinesRequest\x1a\x17.mousewheeld.v1.LineMapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mousewheeld.v1.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGVIEW']._serialized_start=48
  _globals['_CONFIGVIEW']._serialized_end=338
  _globals['_CONFIGPATCH']._serialized_start=341
  _globals['_CONFIGPATCH']._serialized_end=507
  _globals['_LINEMAP']._serialized_start=509
  _globals['_LINEMAP']._serialized_end=561
  _globals['_OUTPUTLINE']._serialized_start=563
  _globals['_OUTPUTLINE']._serialized_end=647
  _globals['_READCONFIGREQUEST']._serialized_start=649
  _globals['_READCONFIGREQUEST']._serialized_end=668
  _globals['_READLINESREQUEST']._serialized_start=670
  _globals['_READLINESREQUEST']._serialized_end=688
  _globals['_CONFIG']._serialized_start=691
  _globals['_CONFIG']._serialized_end=920
# @@protoc_insertion_point(module_scope)
