# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mousewheeld.v1 import state_pb2 as mousewheeld_dot_v1_dot_state__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mousewheeld/v1/state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateServiceStub:
    """Where the wheel is.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadState = channel.unary_unary(
                '/mousewheeld.v1.StateService/ReadState',
                request_serializer=mousewheeld_dot_v1_dot_state__pb2.ReadStateRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_state__pb2.RigState.FromString,
                _registered_method=True)
        self.WatchState = channel.unary_stream(
                '/mousewheeld.v1.StateService/WatchState',
                request_serializer=mousewheeld_dot_v1_dot_state__pb2.WatchStateRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_state__pb2.StreamFrame.FromString,
                _registered_method=True)
        self.ZeroPosition = channel.unary_unary(
                '/mousewheeld.v1.StateService/ZeroPosition',
                request_serializer=mousewheeld_dot_v1_dot_state__pb2.ZeroRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_state__pb2.RigState.FromString,
                _registered_method=True)


class StateServiceServicer:
    """Where the wheel is.
    """

    def ReadState(self, request, context):
        """Everything true right now, per axis, with the link health that says
        whether to believe it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchState(self, request, context):
        """The decimated path, as it happens.

        `rate_hz` is a query parameter and is what the browser asks for, **not**
        what the device samples at: the daemon decimates and says what it lost.
        A consumer breaks its line on `lost_before` and on nothing else.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZeroPosition(self, request, context):
        """Move the **API origin** — what displacement, distance and the zones are
        measured from.

        Never the accumulator published to a camera: vstimd differences that every
        frame, and a value that jumps backwards jumps the corridor backwards.
        Teleporting a corridor is a command to vstimd, from whoever runs the
        experiment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadState,
                    request_deserializer=mousewheeld_dot_v1_dot_state__pb2.ReadStateRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_state__pb2.RigState.SerializeToString,
            ),
            'WatchState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchState,
                    request_deserializer=mousewheeld_dot_v1_dot_state__pb2.WatchStateRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_state__pb2.StreamFrame.SerializeToString,
            ),
            'ZeroPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ZeroPosition,
                    request_deserializer=mousewheeld_dot_v1_dot_state__pb2.ZeroRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_state__pb2.RigState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mousewheeld.v1.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mousewheeld.v1.StateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateService:
    """Where the wheel is.
    """

    @staticmethod
    def ReadState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.StateService/ReadState',
            mousewheeld_dot_v1_dot_state__pb2.ReadStateRequest.SerializeToString,
            mousewheeld_dot_v1_dot_state__pb2.RigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mousewheeld.v1.StateService/WatchState',
            mousewheeld_dot_v1_dot_state__pb2.WatchStateRequest.SerializeToString,
            mousewheeld_dot_v1_dot_state__pb2.StreamFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZeroPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.StateService/ZeroPosition',
            mousewheeld_dot_v1_dot_state__pb2.ZeroRequest.SerializeToString,
            mousewheeld_dot_v1_dot_state__pb2.RigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
