# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from mousewheeld.v1 import device_pb2 as mousewheeld_dot_v1_dot_device__pb2
from mousewheeld.v1 import zones_pb2 as mousewheeld_dot_v1_dot_zones__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mousewheeld/v1/zones_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZonesStub:
    """Distances at which a line fires.

    **Zones are dynamic; the lines they drive are not.** A zone set names
    `"line": "zone_goal"` and never a pin, so one set runs on every rig that has
    a `zone_goal` line and a rewired rig edits one file.

    **Authored in centimetres, compiled to counts.** The firmware has no
    floating point on any path whose result crosses the wire, so the host turns
    every centimetre into an integer interval before the board sees it — against
    a named calibration, which is why changing the calibration marks compiled
    sets stale.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListZoneSets = channel.unary_unary(
                '/mousewheeld.v1.Zones/ListZoneSets',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ListZoneSetsRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetNames.FromString,
                _registered_method=True)
        self.ReadZoneSet = channel.unary_unary(
                '/mousewheeld.v1.Zones/ReadZoneSet',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.FromString,
                _registered_method=True)
        self.ReplaceZoneSet = channel.unary_unary(
                '/mousewheeld.v1.Zones/ReplaceZoneSet',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.WriteZoneSet.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.FromString,
                _registered_method=True)
        self.ValidateDraft = channel.unary_unary(
                '/mousewheeld.v1.Zones/ValidateDraft',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.FromString,
                _registered_method=True)
        self.ValidateZoneSet = channel.unary_unary(
                '/mousewheeld.v1.Zones/ValidateZoneSet',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.FromString,
                _registered_method=True)
        self.ReadZoneSetSchema = channel.unary_unary(
                '/mousewheeld.v1.Zones/ReadZoneSetSchema',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ReadZoneSetSchemaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.ReadZoneSetFile = channel.unary_unary(
                '/mousewheeld.v1.Zones/ReadZoneSetFile',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.FromString,
                _registered_method=True)
        self.WriteZoneSetFile = channel.unary_unary(
                '/mousewheeld.v1.Zones/WriteZoneSetFile',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.FromString,
                _registered_method=True)
        self.ValidateZoneSetFile = channel.unary_unary(
                '/mousewheeld.v1.Zones/ValidateZoneSetFile',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.FromString,
                _registered_method=True)
        self.ReadArmed = channel.unary_unary(
                '/mousewheeld.v1.Zones/ReadArmed',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ReadArmedRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.FromString,
                _registered_method=True)
        self.Arm = channel.unary_unary(
                '/mousewheeld.v1.Zones/Arm',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.ArmRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.FromString,
                _registered_method=True)
        self.Disarm = channel.unary_unary(
                '/mousewheeld.v1.Zones/Disarm',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.DisarmRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.FromString,
                _registered_method=True)
        self.SaveToFlash = channel.unary_unary(
                '/mousewheeld.v1.Zones/SaveToFlash',
                request_serializer=mousewheeld_dot_v1_dot_zones__pb2.SaveToFlashRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.FromString,
                _registered_method=True)


class ZonesServicer:
    """Distances at which a line fires.

    **Zones are dynamic; the lines they drive are not.** A zone set names
    `"line": "zone_goal"` and never a pin, so one set runs on every rig that has
    a `zone_goal` line and a rewired rig edits one file.

    **Authored in centimetres, compiled to counts.** The firmware has no
    floating point on any path whose result crosses the wire, so the host turns
    every centimetre into an integer interval before the board sees it — against
    a named calibration, which is why changing the calibration marks compiled
    sets stale.
    """

    def ListZoneSets(self, request, context):
        """The names in the store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadZoneSet(self, request, context):
        """One stored set, exactly as it is on disk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceZoneSet(self, request, context):
        """Store a set. Refused if it does not parse or does not compile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateDraft(self, request, context):
        """Compile a **draft** — what somebody is typing, before it is saved.

        The body goes through the daemon's own deserializer and compiler, so what
        comes back is the refusal the real thing would give. There is no second,
        looser description of a zone set in a browser to disagree with it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateZoneSet(self, request, context):
        """Compile the set as it is **stored** — "is that one still good after the
        calibration changed".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadZoneSetSchema(self, request, context):
        """The JSON Schema of a zone set **file**, for an editor or a checker.

        Not the schema of `ZoneSet` above — that one is this file, and a client
        generates from it. This is the stored spelling: `"$goal_cm"` for a
        reference, `"displacement"` for a metric, which is what somebody has open
        in an editor. Arbitrary JSON, so it is carried as such.

        Committed in this repository as well, at
        `docs/reference/zone-set.schema.json`, because an editor and CI must reach
        it without a daemon running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadZoneSetFile(self, request, context):
        """The same three, on the **file** rather than the message.

        A zone set has two spellings and always has: the message above, which a
        generated client builds, and the file on disk, which a person edits and
        copies between rigs. `ReadZoneSet` gives the first. These give the second,
        as the text it is, because an editor with a cursor in it is editing bytes —
        and a browser that converted between the two spellings itself would be the
        second, looser description of a zone set that this service exists to avoid.

        The daemon parses with its own deserializer, so what comes back is the
        refusal a hand-edited file would earn, with the line and column in it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteZoneSetFile(self, request, context):
        """Parse, compile, and store. Answers with the file as it was written, which
        is the canonical spelling — an editor shows what is on disk, not what was
        typed at it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateZoneSetFile(self, request, context):
        """Parse and compile a file that is not in the store. `name` may be empty:
        this is a draft.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArmed(self, request, context):
        """What is armed, what fired, and where.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Arm(self, request, context):
        """Resolve the patch, compile against the calibration in force, upload, and
        wait for the board to answer `armed`.

        Refuses when the set does not fit, naming what overflowed; refuses a
        `$name` the patch does not carry, naming the name. Never a default — a
        goal distance that silently became zero is a trial that looks like it ran.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveToFlash(self, request, context):
        """Write what is armed to the board's flash, so a standalone rig comes up
        with its zones. Refuses `nothing_armed`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZonesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListZoneSets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListZoneSets,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ListZoneSetsRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetNames.SerializeToString,
            ),
            'ReadZoneSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadZoneSet,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.SerializeToString,
            ),
            'ReplaceZoneSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceZoneSet,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.WriteZoneSet.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.SerializeToString,
            ),
            'ValidateDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateDraft,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.SerializeToString,
            ),
            'ValidateZoneSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateZoneSet,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.SerializeToString,
            ),
            'ReadZoneSetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadZoneSetSchema,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ReadZoneSetSchemaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'ReadZoneSetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadZoneSetFile,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.SerializeToString,
            ),
            'WriteZoneSetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteZoneSetFile,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.SerializeToString,
            ),
            'ValidateZoneSetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateZoneSetFile,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.SerializeToString,
            ),
            'ReadArmed': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArmed,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ReadArmedRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.SerializeToString,
            ),
            'Arm': grpc.unary_unary_rpc_method_handler(
                    servicer.Arm,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.ArmRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.SerializeToString,
            ),
            'Disarm': grpc.unary_unary_rpc_method_handler(
                    servicer.Disarm,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.DisarmRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.SerializeToString,
            ),
            'SaveToFlash': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveToFlash,
                    request_deserializer=mousewheeld_dot_v1_dot_zones__pb2.SaveToFlashRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mousewheeld.v1.Zones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mousewheeld.v1.Zones', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Zones:
    """Distances at which a line fires.

    **Zones are dynamic; the lines they drive are not.** A zone set names
    `"line": "zone_goal"` and never a pin, so one set runs on every rig that has
    a `zone_goal` line and a rewired rig edits one file.

    **Authored in centimetres, compiled to counts.** The firmware has no
    floating point on any path whose result crosses the wire, so the host turns
    every centimetre into an integer interval before the board sees it — against
    a named calibration, which is why changing the calibration marks compiled
    sets stale.
    """

    @staticmethod
    def ListZoneSets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ListZoneSets',
            mousewheeld_dot_v1_dot_zones__pb2.ListZoneSetsRequest.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetNames.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadZoneSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ReadZoneSet',
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceZoneSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ReplaceZoneSet',
            mousewheeld_dot_v1_dot_zones__pb2.WriteZoneSet.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ValidateDraft',
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSet.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateZoneSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ValidateZoneSet',
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadZoneSetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ReadZoneSetSchema',
            mousewheeld_dot_v1_dot_zones__pb2.ReadZoneSetSchemaRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadZoneSetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ReadZoneSetFile',
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetName.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteZoneSetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/WriteZoneSetFile',
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateZoneSetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ValidateZoneSetFile',
            mousewheeld_dot_v1_dot_zones__pb2.ZoneSetFile.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ValidationReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadArmed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/ReadArmed',
            mousewheeld_dot_v1_dot_zones__pb2.ReadArmedRequest.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Arm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/Arm',
            mousewheeld_dot_v1_dot_zones__pb2.ArmRequest.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/Disarm',
            mousewheeld_dot_v1_dot_zones__pb2.DisarmRequest.SerializeToString,
            mousewheeld_dot_v1_dot_zones__pb2.ArmedZones.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveToFlash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Zones/SaveToFlash',
            mousewheeld_dot_v1_dot_zones__pb2.SaveToFlashRequest.SerializeToString,
            mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
