// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Route {
    /// `GET`, `POST`, `PUT`, `PATCH`, `DELETE`. For a websocket it is the method
    /// of the upgrade request, which is always `GET`.
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    /// `/api/zones/arm`, with `{name}` for a path parameter — the spelling axum
    /// and every other router in the family already uses.
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// Which part of the request message is the body: `*` for the whole message,
    /// a field name for one field, empty for a request that has no body and
    /// carries its fields in the path or the query string.
    #[prost(string, tag = "3")]
    pub body: ::prost::alloc::string::String,
    /// The route is a websocket the server pushes frames down. The rpc is then
    /// `returns (stream T)`, and the client opens a socket rather than calling.
    ///
    /// This is the one thing OpenAPI could not say, which is why three of this
    /// family's four streams were specified only in prose until now.
    #[prost(bool, tag = "4")]
    pub websocket: bool,
}
