// SPDX-License-Identifier: AGPL-3.0-or-later
//! The API's types, generated from `proto/mousewheeld/v1/`.
//!
//! **Nothing outside `api/` and `convert/` names a type from here.** These are
//! the shapes on the wire; `model/` holds the shapes this daemon thinks in, and
//! `convert/` is the seam between them. That separation is what lets a file on
//! disk and a message on a wire differ where they should — a zone set is
//! `"$goal_cm"` in an editor and a `ZoneBound` here — and what would let the
//! wire format change without the daemon noticing.
//!
//! Generated by `make proto` and **committed**, so a checkout builds with cargo
//! alone, a reviewer sees an interface change in a diff, and the types can be
//! read rather than inferred from a build directory. Do not edit by hand:
//! `make check-proto` regenerates and fails if the result differs.

#![allow(clippy::all)]

include!("mousewheeld.v1.rs");
include!("mousewheeld.v1.serde.rs");

/// THE SPIKE: the `service` blocks, as traits a daemon implements.
///
/// Generated by tonic from the same `.proto`. An rpc with no implementation is
/// a compile error, which is the job `tools/check_routes.py` does by reading
/// source code.
pub mod service {
    use super::*;
    include!("service/mousewheeld.v1.rs");
}

/// The descriptor set, for server reflection — the standard answer to "what
/// does this daemon speak", which `/api/proto` was invented to substitute for.
pub const DESCRIPTOR: &[u8] = include_bytes!("descriptor_for_reflection.bin");
