// SPDX-License-Identifier: AGPL-3.0-or-later
//! The API's types, generated from `proto/mousewheeld/v1/`, and the board's
//! link, from `proto/mousewheeld/link/v1/`.
//!
//! **Nothing outside `grpc/` and `convert/` names a type from here.** These are
//! the shapes on the wire; `model/` holds the shapes this daemon thinks in, and
//! `convert/` is the seam between them. That separation is what lets a file on
//! disk and a message on a wire differ where they should — a zone set is
//! `"$goal_cm"` in an editor and a `ZoneBound` here — and what would let the
//! wire format change without the daemon noticing.
//!
//! Generated by `make proto` and **committed**, so a checkout builds with cargo
//! alone, a reviewer sees an interface change in a diff, and the types can be
//! read rather than inferred from a build directory. Do not edit by hand:
//! `make check-proto` regenerates and fails if the result differs.

#![allow(clippy::all)]

include!("mousewheeld.v1.rs");

/// The `service` blocks, as traits the daemon implements.
///
/// **An rpc with no implementation is a compile error.** That is the whole of
/// the route checking this repository used to do by reading source code with
/// regexes, and it is now the type system's.
pub mod service {
    // The generated code names `super::` types by full path, so nothing is
    // imported here; the module exists to hold the include.
    #[allow(unused_imports)]
    use super::*;
    include!("service/mousewheeld.v1.rs");
}

/// The schema, for server reflection.
///
/// How a client discovers what this daemon speaks — every service, every rpc,
/// argument and return types — without having the `.proto` to hand. It is the
/// convention a `/api/proto` route would only be a worse version of.
pub const DESCRIPTOR: &[u8] = include_bytes!("descriptor_for_reflection.bin");

/// The board's link: what the daemon and the firmware say to each other, in
/// counts. **The one exception to the rule above:** these are named by `link/`
/// and `device/`, because the link *is* the shape on that wire, and the device
/// module is the seam between it and `model/`. Nothing else names them.
pub mod link {
    include!("link/mousewheeld.link.v1.rs");
}
