// This file is @generated by prost-build.
/// Named `CalibrationState` and not `Calibration`: the service already holds
/// that name, and a message and a service sharing one is legal in protobuf and
/// confusing in every language it generates.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CalibrationState {
    #[prost(message, repeated, tag = "1")]
    pub axes: ::prost::alloc::vec::Vec<AxisCalibration>,
    /// The ball's transform. Always absent today.
    #[prost(message, optional, tag = "2")]
    pub ball: ::core::option::Option<BallCalibration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AxisCalibration {
    /// The axis this describes, matching the axis names everywhere else.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Counts per centimetre of travel at the running surface. The number that
    /// converts the device's only unit into everybody else's.
    #[prost(double, tag = "2")]
    pub counts_per_cm: f64,
    /// Encoder counts per revolution, after quadrature ×4. Kept for the
    /// arithmetic a measurement is checked against — a whole-number ratio between
    /// the two is a decoder counting ×1 or ×2, not a wheel of the wrong size.
    #[prost(uint32, optional, tag = "3")]
    pub counts_per_rev: ::core::option::Option<u32>,
    /// The wheel's diameter — a full extent, never a radius. Porting from a
    /// package that specifies radii means doubling at the boundary.
    #[prost(double, optional, tag = "4")]
    pub diameter_cm: ::core::option::Option<f64>,
    /// Count the other way. Applied by the device to its own accumulator, so
    /// everything downstream reads a wheel that turns forwards. A sign applied in
    /// two places is a sign applied in neither.
    #[prost(bool, tag = "5")]
    pub invert: bool,
    /// When `counts_per_cm` was last measured rather than computed. Absent is not
    /// a missing field: it means nobody has ever rolled this wheel against a
    /// tape, and the panels say so.
    #[prost(string, optional, tag = "6")]
    pub measured_at: ::core::option::Option<::prost::alloc::string::String>,
}
/// Declared, refused, and here so the shape of the answer is not a surprise.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BallCalibration {
    #[prost(double, tag = "1")]
    pub diameter_cm: f64,
    /// Where each sensor sits, in degrees around the ball.
    #[prost(double, repeated, tag = "2")]
    pub sensor_angles_deg: ::prost::alloc::vec::Vec<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CalibrationPatch {
    #[prost(message, repeated, tag = "1")]
    pub axes: ::prost::alloc::vec::Vec<AxisCalibrationPatch>,
}
/// Everything optional but the name, so a panel can send one field.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AxisCalibrationPatch {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, optional, tag = "2")]
    pub counts_per_cm: ::core::option::Option<f64>,
    #[prost(uint32, optional, tag = "3")]
    pub counts_per_rev: ::core::option::Option<u32>,
    #[prost(double, optional, tag = "4")]
    pub diameter_cm: ::core::option::Option<f64>,
    #[prost(bool, optional, tag = "5")]
    pub invert: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartMeasurement {
    #[prost(string, tag = "1")]
    pub axis: ::prost::alloc::string::String,
    /// How far the wheel is about to be rolled, by hand, along its running
    /// surface, in the direction the animal runs. A metre in one continuous
    /// motion: a metre averages away where you started and stopped, and one
    /// revolution does not.
    #[prost(double, tag = "2")]
    pub known_distance_cm: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeasurementStarted {
    #[prost(string, tag = "1")]
    pub axis: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub known_distance_cm: f64,
    /// The counter when counting began, so a UI can show progress without asking
    /// the daemon to keep a second copy of it.
    #[prost(int64, tag = "3")]
    pub counts_at_start: i64,
    #[prost(int64, tag = "4")]
    pub counts: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeasurementResult {
    #[prost(string, tag = "1")]
    pub axis: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub known_distance_cm: f64,
    #[prost(int64, tag = "3")]
    pub counts: i64,
    #[prost(double, tag = "4")]
    pub measured_counts_per_cm: f64,
    #[prost(double, tag = "5")]
    pub configured_counts_per_cm: f64,
    #[prost(uint32, optional, tag = "6")]
    pub counts_per_rev: ::core::option::Option<u32>,
    /// What the wheel's stated dimensions imply — the arithmetic this measurement
    /// exists to correct. On the report rather than left to a client, so a result
    /// is readable on its own a month later.
    #[prost(double, optional, tag = "7")]
    pub nominal_counts_per_cm: ::core::option::Option<f64>,
    /// The circumference the measurement implies, when the counts per revolution
    /// are known — the number to hold against the wheel with a tape.
    #[prost(double, optional, tag = "8")]
    pub implied_circumference_cm: ::core::option::Option<f64>,
    /// Set when the measurement is a whole-number multiple of the configured
    /// value: a decoding mistake rather than a wheel, and worth saying in words
    /// before somebody applies it.
    #[prost(string, optional, tag = "9")]
    pub decoding_suspect: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeasurementApplied {
    #[prost(string, tag = "1")]
    pub axis: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub counts_per_cm: f64,
    /// Compiled zone sets are stale now, and the next arm recompiles.
    #[prost(bool, tag = "3")]
    pub zone_sets_invalidated: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadCalibrationRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadBallRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinishMeasuringRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyMeasurementRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigView {
    /// What the device is asked to send. Cumulative counts, so a lower rate costs
    /// resolution and never distance.
    #[prost(uint32, tag = "1")]
    pub rate_hz: u32,
    /// The refresh rate of the display this wheel drives, when it drives one.
    /// Zero means no display follows this wheel.
    #[prost(uint32, tag = "2")]
    pub display_hz: u32,
    /// How long the in-memory path stays queryable.
    #[prost(uint32, tag = "3")]
    pub ring_minutes: u32,
    /// The vinput segment name. vstimd's rig config names the same string and
    /// never learns who writes it.
    #[prost(string, tag = "4")]
    pub shm_name: ::prost::alloc::string::String,
    /// Whether that segment is actually open. A name in a config file and a
    /// mapped segment are different things, and the difference is the whole
    /// reason a corridor sometimes does not move.
    #[prost(bool, tag = "5")]
    pub shm_open: bool,
    /// Writes that have reached it since it was created.
    #[prost(uint64, tag = "6")]
    pub shm_writes: u64,
    /// The ZMQ PUB port, after vstimd's 5555 REP and 5556 events.
    #[prost(uint32, tag = "7")]
    pub event_port: u32,
    /// Read-only here: wiring is changed where wiring is described.
    #[prost(string, tag = "8")]
    pub port: ::prost::alloc::string::String,
    /// True when `rate_hz` is at or below `display_hz`. Below the display rate
    /// some frames see no new sample and the next sees two, and the corridor
    /// moves in uneven steps at exactly the speeds a running animal produces.
    #[prost(bool, tag = "9")]
    pub starves_the_display: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigPatch {
    #[prost(uint32, optional, tag = "1")]
    pub rate_hz: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub display_hz: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub ring_minutes: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LineMap {
    #[prost(message, repeated, tag = "1")]
    pub lines: ::prost::alloc::vec::Vec<OutputLine>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutputLine {
    /// What a zone set calls it.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The board's own index for this line — what the wire carries, since the
    /// device protocol is indices and not names.
    #[prost(uint32, tag = "2")]
    pub index: u32,
    /// The pin it is wired to, on this board.
    #[prost(uint32, tag = "3")]
    pub pin: u32,
    /// The level the firmware drives when nothing else says otherwise. Outputs
    /// reach this before anything else runs.
    #[prost(bool, tag = "4")]
    pub safe_high: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadConfigRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadLinesRequest {}
/// What this daemon is, and what it speaks.
///
/// A console shows three daemons' panels beside each other and needs to know
/// what it is showing; a client that wants a field added last month needs to
/// know whether it is there. Both are answered by **advertising** a version,
/// never by gating on one — a version check between daemons turns every upgrade
/// into a coordinated one, on a rig whose whole arrangement is that each daemon
/// runs alone (`contracts/INTERACTIONS.md` §11).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VersionReport {
    /// This daemon's release, from the build.
    #[prost(string, tag = "1")]
    pub daemon: ::prost::alloc::string::String,
    /// The API contract's major version. Within it, changes are additive: fields,
    /// routes and enum values may appear; nothing is removed, renamed or given a
    /// new meaning. Deliberately slower-moving than the release.
    #[prost(uint32, tag = "2")]
    pub api: u32,
    #[prost(message, optional, tag = "3")]
    pub device_protocol: ::core::option::Option<DeviceProtocol>,
    /// The `vinput` segment layout this daemon writes — the one interface in the
    /// family where a mismatch is bytes reinterpreted rather than a field gone
    /// missing, and therefore the one that is checked rather than advertised. The
    /// reader refuses to map a segment whose version is not its own; this is here
    /// so a person can see why before it happens.
    #[prost(uint32, tag = "4")]
    pub vinput_layout: u32,
}
/// The wire to the board: what this daemon sends, the oldest it will talk to,
/// and what the attached board actually said.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceProtocol {
    /// What this daemon sends in `hello`.
    #[prost(uint32, tag = "1")]
    pub speaks: u32,
    /// The oldest it will talk to. Below this a board is refused by name rather
    /// than half-understood.
    #[prost(uint32, tag = "2")]
    pub floor: u32,
    /// What the attached board greeted with, if one has. Absent, not zero, when
    /// nothing has connected — zero is a protocol version somebody could ship.
    #[prost(uint32, optional, tag = "3")]
    pub board: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceInfo {
    #[prost(bool, tag = "1")]
    pub connected: bool,
    /// The serial port this daemon owns, from the rig config.
    #[prost(string, tag = "2")]
    pub port: ::prost::alloc::string::String,
    /// `teensy41`, `esp32`, or `simulated`.
    #[prost(string, tag = "3")]
    pub board: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub firmware_version: ::prost::alloc::string::String,
    /// The wire protocol version the board greeted with.
    #[prost(uint32, tag = "5")]
    pub protocol_version: u32,
    /// The board's clock since it booted — a reset shows up here before it shows
    /// up anywhere else. Microseconds, and a string in JSON, as every 64-bit
    /// integer in this API is.
    #[prost(uint64, tag = "6")]
    pub uptime_device_us: u64,
    #[prost(message, optional, tag = "7")]
    pub capacities: ::core::option::Option<Capacities>,
    /// The set written to the board's flash, if any: a standalone rig comes up
    /// with its zones, and the board reports which copy it holds.
    #[prost(message, optional, tag = "8")]
    pub flashed_zone_set: ::core::option::Option<FlashedZoneSet>,
    #[prost(message, optional, tag = "9")]
    pub link: ::core::option::Option<LinkStats>,
}
/// Compile-time limits, reported by the board at `hello`.
///
/// Here because a zone set that does not fit must be refused at upload naming
/// what overflowed, not discovered on a rig at three in the morning.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Capacities {
    /// Narrower than a uint32 in the firmware; protobuf has no smaller integer,
    /// and inventing one would put a second bound in a second place.
    #[prost(uint32, tag = "1")]
    pub n_axes: u32,
    #[prost(uint32, tag = "2")]
    pub max_zones: u32,
    #[prost(uint32, tag = "3")]
    pub max_lines: u32,
    /// The scan the firmware runs its counters and zones at.
    #[prost(uint32, tag = "4")]
    pub scan_hz: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlashedZoneSet {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub version: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkStats {
    /// How many times this daemon has (re)connected to a board. A number that
    /// climbs on its own is a cable.
    #[prost(uint64, tag = "1")]
    pub connection_count: u64,
    /// The last thing the board refused, kept because it is usually the answer.
    #[prost(string, optional, tag = "2")]
    pub last_error: ::core::option::Option<::prost::alloc::string::String>,
}
/// One line of the wire, either direction, uninterpreted.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WireLine {
    #[prost(uint64, tag = "1")]
    pub host_monotonic_ns: u64,
    #[prost(enumeration = "WireDirection", tag = "2")]
    pub direction: i32,
    #[prost(string, tag = "3")]
    pub text: ::prost::alloc::string::String,
    #[prost(enumeration = "WireLevel", tag = "4")]
    pub level: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WireLog {
    #[prost(message, repeated, tag = "1")]
    pub lines: ::prost::alloc::vec::Vec<WireLine>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FirmwareVersions {
    /// What the attached board is running.
    #[prost(string, tag = "1")]
    pub running: ::prost::alloc::string::String,
    /// What this daemon ships and could flash. Empty until the firmware exists.
    #[prost(string, repeated, tag = "2")]
    pub available: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadVersionRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadDeviceRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenLinkRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadFirmwareRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadWireLogRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchWireRequest {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WireDirection {
    Unspecified = 0,
    /// daemon → board
    Out = 1,
    /// board → daemon
    In = 2,
}
impl WireDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WIRE_DIRECTION_UNSPECIFIED",
            Self::Out => "WIRE_DIRECTION_OUT",
            Self::In => "WIRE_DIRECTION_IN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WIRE_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "WIRE_DIRECTION_OUT" => Some(Self::Out),
            "WIRE_DIRECTION_IN" => Some(Self::In),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WireLevel {
    Unspecified = 0,
    Info = 1,
    /// A line the board refused, or one that failed its CRC.
    Error = 2,
}
impl WireLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WIRE_LEVEL_UNSPECIFIED",
            Self::Info => "WIRE_LEVEL_INFO",
            Self::Error => "WIRE_LEVEL_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WIRE_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "WIRE_LEVEL_INFO" => Some(Self::Info),
            "WIRE_LEVEL_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
/// One refusal shape, for every route.
///
/// A machine-readable code, a sentence, and the thing to change. The third
/// field is the one that earns its keep: a zone set that does not fit names
/// what overflowed, and a UI that can only render "409" throws exactly that
/// away. Both clients read all three.
///
/// The HTTP status carries the category — 404 no such thing, 422 understood and
/// refused, 409 not in a state where this means anything, 503 no board, 501
/// designed and not built — and `error` names the particular case within it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    /// Stable and machine-readable: `no_such_zone_set`, `no_device`.
    /// Additive within an API major version: new codes appear, none change
    /// meaning.
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
    /// One sentence, for a person.
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    /// What to change: a zone set's name, the field that did not fit. May be
    /// empty when the sentence is the whole story.
    #[prost(string, tag = "3")]
    pub context: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchStateRequest {
    /// Frames per second to push. Query parameter, not a body.
    #[prost(uint32, tag = "1")]
    pub rate_hz: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZeroRequest {
    /// Which axes. Empty means all of them.
    #[prost(string, repeated, tag = "1")]
    pub axes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RigState {
    #[prost(message, repeated, tag = "1")]
    pub axes: ::prost::alloc::vec::Vec<AxisState>,
    #[prost(message, optional, tag = "2")]
    pub health: ::core::option::Option<LinkHealth>,
    #[prost(message, optional, tag = "3")]
    pub link: ::core::option::Option<LinkState>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkState {
    #[prost(bool, tag = "1")]
    pub connected: bool,
}
/// Two quantities per axis, and they are not the same question.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AxisState {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The device's 64-bit accumulator. The only unit the firmware knows.
    #[prost(int64, tag = "2")]
    pub counts: i64,
    /// Signed displacement from the origin, `counts − origin`. What a corridor
    /// position is.
    #[prost(double, tag = "3")]
    pub position_cm: f64,
    /// A direction-free odometer since the origin was last moved. What "how much
    /// did it run" is.
    #[prost(double, tag = "4")]
    pub distance_cm: f64,
    /// Computed by the host from the sample path.
    #[prost(double, tag = "5")]
    pub velocity_cm_s: f64,
    /// As the device reported it: counts over a fixed window in its scan, at scan
    /// resolution. Coarser, and the one the analog output and the zone evaluation
    /// were actually done against.
    ///
    /// Both are recorded because they answer different questions, and a record
    /// that silently kept one could not be checked against the other.
    #[prost(double, tag = "6")]
    pub device_velocity_cm_s: f64,
}
/// Whether what the rest of the answer says can be believed.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LinkHealth {
    /// Samples the daemon never received. **A path with a hole in it says so**
    /// rather than reporting a shorter distance that looks complete.
    #[prost(uint64, tag = "1")]
    pub seq_gaps: u64,
    /// The device's own rings overflowed: the firmware telling on itself.
    #[prost(uint64, tag = "2")]
    pub ring_drops: u64,
    /// What the samples are actually arriving at, as opposed to what was asked
    /// for. The two differing is the finding.
    #[prost(double, tag = "3")]
    pub measured_rate_hz: f64,
    /// No sample for longer than the staleness window. Everything above is the
    /// last thing that was true.
    #[prost(bool, tag = "4")]
    pub stale: bool,
}
/// One frame of the state websocket.
///
/// A oneof rather than a `type` discriminator beside flattened fields: the
/// JSON becomes `{"sample": {…}}` instead of `{"type": "sample", …}`, which is
/// a shape change for the panels and the one place a reader cannot mistake
/// which arm they are holding.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamFrame {
    #[prost(oneof = "stream_frame::Frame", tags = "1, 2")]
    pub frame: ::core::option::Option<stream_frame::Frame>,
}
/// Nested message and enum types in `StreamFrame`.
pub mod stream_frame {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Frame {
        #[prost(message, tag = "1")]
        Sample(super::Sample),
        #[prost(message, tag = "2")]
        ZoneHit(super::ZoneHitEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sample {
    /// The device's own sample counter. **Not a loss signal for a consumer**:
    /// this stream is decimated, so `seq` skips by design. See `lost_before`.
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    /// The device clock. Correlating it with the host's is the daemon's job.
    #[prost(uint64, tag = "2")]
    pub device_us: u64,
    /// `CLOCK_MONOTONIC` nanoseconds — the join key with statemachined's trace
    /// and vstimd's vblank timestamps.
    #[prost(uint64, tag = "3")]
    pub host_monotonic_ns: u64,
    /// Samples the daemon **never received** since the previous frame on this
    /// socket, accumulated across the ones decimation dropped. Only the daemon
    /// can tell decimation from loss.
    #[prost(uint64, tag = "4")]
    pub lost_before: u64,
    #[prost(message, repeated, tag = "5")]
    pub axes: ::prost::alloc::vec::Vec<AxisState>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZoneHitEvent {
    #[prost(string, tag = "1")]
    pub zone: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub arm_id: u32,
    #[prost(uint64, tag = "3")]
    pub seq: u64,
    #[prost(uint64, tag = "4")]
    pub host_monotonic_ns: u64,
    #[prost(double, tag = "5")]
    pub position_cm: f64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadStateRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZoneSetNames {
    #[prost(string, repeated, tag = "1")]
    pub zone_sets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A set's name in the store. A path parameter, never a body.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZoneSetName {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteZoneSet {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub zone_set: ::core::option::Option<ZoneSet>,
}
/// A named set, as the API carries it.
///
/// **The file on disk is a storage format, not this.** A stored zone set keeps
/// its own spelling — a bound written `"$goal_cm"`, a metric written
/// `"displacement"` — because somebody edits it in a text editor and reviews it
/// in a diff, and `docs/reference/zone-set.schema.json` is its schema. The
/// daemon converts at the same seam it converts everything else, exactly as it
/// does for the TOML rig config.
///
/// This was carried as an opaque document at first, to keep one spelling for
/// both. That put the one part of the API a client most wants to construct
/// beyond the reach of a type, and a schema for it in a second file. The public
/// interface is defined in one place and strongly typed, or it is not; the file
/// keeps its own shape and the daemon pays for the difference.
///
/// Declaration order resolves two zones firing in one scan: both still fire,
/// and the order is the order of their `zone_hit` messages.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZoneSet {
    /// A URL for this set's JSON Schema, carried so an editor can validate the
    /// *file* as somebody types it. Stored as `$schema`; named for what it is
    /// here, since a leading `$` is a JSON-editor convention and not a field name.
    ///
    /// It exists because the file refuses unknown fields: without somewhere to put
    /// it, the one line that makes a hand-edited file checkable would itself be a
    /// refusal.
    #[prost(string, optional, tag = "1")]
    pub schema_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Bumped by whoever edits the set. The board reports the version it holds, so
    /// "is the board running what I think it is" is one comparison.
    #[prost(uint32, tag = "2")]
    pub zone_set_version: u32,
    #[prost(message, repeated, tag = "3")]
    pub zones: ::prost::alloc::vec::Vec<Zone>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Zone {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ZoneShape", tag = "2")]
    pub shape: i32,
    /// The axes this zone constrains, in the order its bounds are given. One for a
    /// wheel; a 2-D rectangle on a ball is already expressible.
    #[prost(string, repeated, tag = "3")]
    pub axes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "ZoneMetric", tag = "4")]
    pub metric: i32,
    /// The low end per axis, in the order of `axes`.
    #[prost(message, repeated, tag = "5")]
    pub min_cm: ::prost::alloc::vec::Vec<ZoneBound>,
    /// The high end per axis.
    #[prost(message, repeated, tag = "6")]
    pub max_cm: ::prost::alloc::vec::Vec<ZoneBound>,
    /// A circular track: the metric is evaluated modulo this period.
    #[prost(double, optional, tag = "7")]
    pub wrap_cm: ::core::option::Option<f64>,
    #[prost(enumeration = "FireRule", tag = "8")]
    pub fire: i32,
    #[prost(double, optional, tag = "9")]
    pub hysteresis_cm: ::core::option::Option<f64>,
    /// Fire on arming if the animal is already inside. Off by default: a zone
    /// fires on the false→true **edge** of "inside", so arming a zone somebody is
    /// standing in does not fire it.
    #[prost(bool, tag = "10")]
    pub level: bool,
    #[prost(message, optional, tag = "11")]
    pub output: ::core::option::Option<ZoneOutput>,
}
/// One end of a zone's interval on one axis.
///
/// Three things, and they are not interchangeable: a number, an **open** bound
/// (neither arm set — "everything past here"), and a **reference** to a
/// per-trial value resolved from the patch given at arm time.
///
/// A reference that reaches the compiler unresolved is a refusal naming the
/// name, never a zero: a goal distance that silently became zero is a trial that
/// looks like it ran. The board never sees a reference; substitution happens
/// host-side, before compilation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZoneBound {
    #[prost(oneof = "zone_bound::Bound", tags = "1, 2")]
    pub bound: ::core::option::Option<zone_bound::Bound>,
}
/// Nested message and enum types in `ZoneBound`.
pub mod zone_bound {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Bound {
        #[prost(double, tag = "1")]
        Value(f64),
        /// The name without its `$`. The file writes `"$goal_cm"`; the sigil is the
        /// file's way of telling a number from a name in one JSON position, and the
        /// oneof is this interface's.
        #[prost(string, tag = "2")]
        Reference(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZoneOutput {
    /// A **name** from the rig config's line map, never a pin number.
    #[prost(string, tag = "1")]
    pub line: ::prost::alloc::string::String,
    #[prost(enumeration = "OutputAction", tag = "2")]
    pub action: i32,
    /// Pulse width. Ignored by a `level` output.
    #[prost(uint32, optional, tag = "3")]
    pub ms: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArmRequest {
    /// A name from the store. Never a slot: the daemon holds the sets, and a name
    /// it does not have is a configuration error the caller can report.
    #[prost(string, tag = "1")]
    pub zone_set: ::prost::alloc::string::String,
    /// Per-trial values for this set's `$name` bounds.
    #[prost(btree_map = "string, double", tag = "2")]
    pub patch: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        f64,
    >,
    #[prost(enumeration = "ArmOrigin", tag = "3")]
    pub origin: i32,
    /// Opaque text stored with the arm — triald writes `trial 42`. The daemon
    /// stays trial-blind and hands it back unread.
    #[prost(string, optional, tag = "4")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArmedZones {
    #[prost(string, optional, tag = "1")]
    pub zone_set: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub zone_set_version: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub arm_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "5")]
    pub zones: ::prost::alloc::vec::Vec<ZoneStatus>,
}
/// What a zone is doing right now.
///
/// The bounds are **as armed**, in centimetres: the `$name`s resolved from the
/// trial's patch and the counts the board is actually comparing against,
/// converted back. Without them a UI can only draw the set as *stored*, which
/// for a parameterised set is a picture of a zone that is not the one running —
/// and "is the reward region where I think it is" is the question the picture
/// exists to answer.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZoneStatus {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub armed: bool,
    #[prost(bool, tag = "3")]
    pub fired: bool,
    #[prost(bool, tag = "4")]
    pub inside: bool,
    #[prost(double, optional, tag = "5")]
    pub fired_at_cm: ::core::option::Option<f64>,
    /// Per axis, in the order the zone names them. An absent value is an open
    /// bound — everything past the other end.
    ///
    /// A **resolved** bound, deliberately a different type from `ZoneBound`: what
    /// is armed can no longer be a `$name`, and the type saying so is the point of
    /// having types.
    #[prost(message, repeated, tag = "6")]
    pub min_cm: ::prost::alloc::vec::Vec<ResolvedBound>,
    #[prost(message, repeated, tag = "7")]
    pub max_cm: ::prost::alloc::vec::Vec<ResolvedBound>,
    /// The period the metric is taken modulo, if the zone wraps.
    #[prost(double, optional, tag = "8")]
    pub wrap_cm: ::core::option::Option<f64>,
    #[prost(enumeration = "ZoneMetric", tag = "9")]
    pub metric: i32,
}
/// A bound that may be open, after arming resolved it.
///
/// protobuf has no nullable double inside a repeated field, and a repeated
/// `optional double` is not a thing, so the absence has to be carried by a
/// message: `{"value": 30}` or `{}`.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResolvedBound {
    #[prost(double, optional, tag = "1")]
    pub value: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationReport {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// The first thing wrong, in the words the compiler would use. Absent when it
    /// compiles.
    #[prost(string, optional, tag = "2")]
    pub problem: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, tag = "3")]
    pub zone_count: u32,
    /// The calibration it was compiled against, so a report is readable a day
    /// later without guessing which one was in force.
    #[prost(double, tag = "4")]
    pub counts_per_cm: f64,
    /// The `$name`s this set still needs at arm time.
    #[prost(string, repeated, tag = "5")]
    pub references: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListZoneSetsRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadZoneSetSchemaRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadArmedRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisarmRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveToFlashRequest {}
/// The only shape today, and a discriminator rather than a flag: a future
/// `circle` or `polygon` is a new value, and a shape the firmware does not know
/// is refused whole rather than half-evaluated.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ZoneShape {
    Unspecified = 0,
    Rect = 1,
}
impl ZoneShape {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ZONE_SHAPE_UNSPECIFIED",
            Self::Rect => "ZONE_SHAPE_RECT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ZONE_SHAPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ZONE_SHAPE_RECT" => Some(Self::Rect),
            _ => None,
        }
    }
}
/// Which quantity a zone is compared against.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ZoneMetric {
    /// Omitted. Treated as `DISPLACEMENT`, because a corridor is what a wheel
    /// usually drives.
    Unspecified = 0,
    /// Signed, `counts − origin`. What a corridor position is.
    Displacement = 1,
    /// Direction-free odometer, `Σ |Δcounts|`. What "how much did it run" is.
    Distance = 2,
}
impl ZoneMetric {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ZONE_METRIC_UNSPECIFIED",
            Self::Displacement => "ZONE_METRIC_DISPLACEMENT",
            Self::Distance => "ZONE_METRIC_DISTANCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ZONE_METRIC_UNSPECIFIED" => Some(Self::Unspecified),
            "ZONE_METRIC_DISPLACEMENT" => Some(Self::Displacement),
            "ZONE_METRIC_DISTANCE" => Some(Self::Distance),
            _ => None,
        }
    }
}
/// What happens after a zone fires.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FireRule {
    Unspecified = 0,
    /// Disarm after firing.
    Once = 1,
    /// Re-arm once the position has left the zone by `hysteresis_cm`, so encoder
    /// jitter at a boundary is not a pulse train.
    Rearm = 2,
}
impl FireRule {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FIRE_RULE_UNSPECIFIED",
            Self::Once => "FIRE_RULE_ONCE",
            Self::Rearm => "FIRE_RULE_REARM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FIRE_RULE_UNSPECIFIED" => Some(Self::Unspecified),
            "FIRE_RULE_ONCE" => Some(Self::Once),
            "FIRE_RULE_REARM" => Some(Self::Rearm),
            _ => None,
        }
    }
}
/// How the line behaves while the condition holds.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OutputAction {
    Unspecified = 0,
    /// High for at most `ms`.
    Pulse = 1,
    /// High while inside, with the same hysteresis.
    Level = 2,
}
impl OutputAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OUTPUT_ACTION_UNSPECIFIED",
            Self::Pulse => "OUTPUT_ACTION_PULSE",
            Self::Level => "OUTPUT_ACTION_LEVEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OUTPUT_ACTION_UNSPECIFIED" => Some(Self::Unspecified),
            "OUTPUT_ACTION_PULSE" => Some(Self::Pulse),
            "OUTPUT_ACTION_LEVEL" => Some(Self::Level),
            _ => None,
        }
    }
}
/// Where the metric is measured from.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ArmOrigin {
    /// Omitted. Treated as `CURRENT`, which is what a trial wants and what every
    /// caller that does not think about it should get.
    Unspecified = 0,
    /// Displacement and distance are zero at the arm point.
    Current = 1,
    /// Keep the device origin.
    Absolute = 2,
}
impl ArmOrigin {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ARM_ORIGIN_UNSPECIFIED",
            Self::Current => "ARM_ORIGIN_CURRENT",
            Self::Absolute => "ARM_ORIGIN_ABSOLUTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARM_ORIGIN_UNSPECIFIED" => Some(Self::Unspecified),
            "ARM_ORIGIN_CURRENT" => Some(Self::Current),
            "ARM_ORIGIN_ABSOLUTE" => Some(Self::Absolute),
            _ => None,
        }
    }
}
