/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MOUSEWHEELD_LINK_V1_MOUSEWHEELD_LINK_V1_LINK_PB_H_INCLUDED
#define PB_MOUSEWHEELD_LINK_V1_MOUSEWHEELD_LINK_V1_LINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _mousewheeld_link_v1_AxisSource {
    mousewheeld_link_v1_AxisSource_AXIS_SOURCE_QUADRATURE = 0,
    /* Declared so the model is N-axis from day one; refused by name as
 `unsupported_source` until a board can read one. */
    mousewheeld_link_v1_AxisSource_AXIS_SOURCE_OPTICAL_SPI = 1
} mousewheeld_link_v1_AxisSource;

typedef enum _mousewheeld_link_v1_Metric {
    mousewheeld_link_v1_Metric_METRIC_DISPLACEMENT = 0, /* counts − origin, signed */
    mousewheeld_link_v1_Metric_METRIC_DISTANCE = 1 /* Σ|Δcounts| since the origin was set */
} mousewheeld_link_v1_Metric;

typedef enum _mousewheeld_link_v1_Fire {
    mousewheeld_link_v1_Fire_FIRE_ONCE = 0, /* fires on the first entry, then never until re-armed */
    mousewheeld_link_v1_Fire_FIRE_REARM = 1 /* fires again after leaving by `hysteresis` */
} mousewheeld_link_v1_Fire;

typedef enum _mousewheeld_link_v1_Action {
    mousewheeld_link_v1_Action_ACTION_PULSE = 0, /* active for `pulse_ms` */
    mousewheeld_link_v1_Action_ACTION_LEVEL = 1 /* active while engaged */
} mousewheeld_link_v1_Action;

typedef enum _mousewheeld_link_v1_Origin {
    /* Displacement and distance are zero at the arm point — what a trial wants. */
    mousewheeld_link_v1_Origin_ORIGIN_CURRENT = 0,
    /* Keep the device origin. */
    mousewheeld_link_v1_Origin_ORIGIN_ABSOLUTE = 1
} mousewheeld_link_v1_Origin;

typedef enum _mousewheeld_link_v1_AnalogMode {
    mousewheeld_link_v1_AnalogMode_ANALOG_MODE_OFF = 0,
    mousewheeld_link_v1_AnalogMode_ANALOG_MODE_WRAP = 1, /* displacement modulo `range_counts`, a sawtooth */
    mousewheeld_link_v1_AnalogMode_ANALOG_MODE_CLAMP = 2, /* displacement clamped to [lo, hi] */
    mousewheeld_link_v1_AnalogMode_ANALOG_MODE_VELOCITY = 3 /* device velocity, counts/s, clamped to [lo, hi] */
} mousewheeld_link_v1_AnalogMode;

/* Struct definitions */
typedef struct _mousewheeld_link_v1_Hello {
    uint32_t protocol_version;
} mousewheeld_link_v1_Hello;

typedef struct _mousewheeld_link_v1_AxisConfig {
    mousewheeld_link_v1_AxisSource source;
    bool invert;
} mousewheeld_link_v1_AxisConfig;

typedef struct _mousewheeld_link_v1_Axes {
    pb_size_t axes_count;
    mousewheeld_link_v1_AxisConfig axes[2];
} mousewheeld_link_v1_Axes;

typedef struct _mousewheeld_link_v1_Line {
    uint32_t index;
    uint32_t pin;
    /* The idle level. A line is *active* at the other one. */
    bool safe_high;
} mousewheeld_link_v1_Line;

typedef struct _mousewheeld_link_v1_Lines {
    pb_size_t lines_count;
    mousewheeld_link_v1_Line lines[8];
} mousewheeld_link_v1_Lines;

typedef struct _mousewheeld_link_v1_Stream {
    /* Samples per second; 0 stops the stream. At most the board's `scan_hz`. */
    uint32_t rate_hz;
    /* Carry the device's own velocity on each sample. */
    bool velocity;
} mousewheeld_link_v1_Stream;

typedef struct _mousewheeld_link_v1_ZonesBegin {
    uint32_t zone_set_version;
    /* How many `Zone`s follow. `ZonesEnd` is refused unless every index in
 `0..n` arrived. */
    uint32_t n;
    /* The one string the board stores: `HelloAck.flashed` reports a flashed
 set by it. */
    char name[33];
} mousewheeld_link_v1_ZonesBegin;

/* One axis of a rect: an interval in counts. An absent bound is open. */
typedef struct _mousewheeld_link_v1_Interval {
    uint32_t axis;
    bool has_lo;
    int64_t lo;
    bool has_hi;
    int64_t hi;
} mousewheeld_link_v1_Interval;

/* One compiled zone: integer counts, no names, no units. */
typedef struct _mousewheeld_link_v1_Zone {
    uint32_t index;
    pb_size_t intervals_count;
    mousewheeld_link_v1_Interval intervals[2];
    mousewheeld_link_v1_Metric metric;
    /* Period in counts; 0 for a straight track. */
    int64_t wrap;
    mousewheeld_link_v1_Fire fire;
    int64_t hysteresis;
    /* Fire on arming if already inside. */
    bool level_on_arm;
    uint32_t line;
    mousewheeld_link_v1_Action action;
    uint32_t pulse_ms;
} mousewheeld_link_v1_Zone;

typedef struct _mousewheeld_link_v1_ZonesEnd {
    char dummy_field;
} mousewheeld_link_v1_ZonesEnd;

typedef struct _mousewheeld_link_v1_Arm {
    uint32_t arm_id;
    /* Must be the committed set's. A mismatch is refused, so a board that lost
 an upload never arms the set before it. */
    uint32_t zone_set_version;
    mousewheeld_link_v1_Origin origin;
} mousewheeld_link_v1_Arm;

typedef struct _mousewheeld_link_v1_Disarm {
    uint32_t arm_id;
} mousewheeld_link_v1_Disarm;

typedef struct _mousewheeld_link_v1_Zero {
    /* Axis indices; empty for all. */
    pb_size_t axes_count;
    uint32_t axes[2];
} mousewheeld_link_v1_Zero;

typedef struct _mousewheeld_link_v1_Analog {
    uint32_t axis;
    mousewheeld_link_v1_AnalogMode mode;
    int64_t range_counts;
    int64_t lo;
    int64_t hi;
} mousewheeld_link_v1_Analog;

typedef struct _mousewheeld_link_v1_Save {
    char dummy_field;
} mousewheeld_link_v1_Save;

typedef struct _mousewheeld_link_v1_Ping {
    char dummy_field;
} mousewheeld_link_v1_Ping;

typedef struct _mousewheeld_link_v1_StateRequest {
    char dummy_field;
} mousewheeld_link_v1_StateRequest;

/* Human-readable text on the serial port, for a terminal. Left by `Hello`. */
typedef struct _mousewheeld_link_v1_Debug {
    bool on;
} mousewheeld_link_v1_Debug;

/* Everything the daemon sends is one of these. */
typedef struct _mousewheeld_link_v1_HostMessage {
    /* The sender's per-direction counter, wrapping at 16 bits. For link-level
 retry and nothing else — it is not `seq`. */
    uint32_t message_id;
    pb_size_t which_body;
    union {
        mousewheeld_link_v1_Hello hello;
        mousewheeld_link_v1_Axes axes;
        mousewheeld_link_v1_Lines lines;
        mousewheeld_link_v1_Stream stream;
        mousewheeld_link_v1_ZonesBegin zones_begin;
        mousewheeld_link_v1_Zone zone;
        mousewheeld_link_v1_ZonesEnd zones_end;
        mousewheeld_link_v1_Arm arm;
        mousewheeld_link_v1_Disarm disarm;
        mousewheeld_link_v1_Zero zero;
        mousewheeld_link_v1_Analog analog;
        mousewheeld_link_v1_Save save;
        mousewheeld_link_v1_Ping ping;
        mousewheeld_link_v1_StateRequest state;
        mousewheeld_link_v1_Debug debug;
    } body;
} mousewheeld_link_v1_HostMessage;

typedef struct _mousewheeld_link_v1_FlashedSet {
    char name[33];
    uint32_t version;
} mousewheeld_link_v1_FlashedSet;

/* Sent in reply to `Hello`, and unasked at boot — which is how the daemon
 learns the board reset. */
typedef struct _mousewheeld_link_v1_HelloAck {
    char board[24];
    char firmware[32];
    uint32_t protocol_version;
    uint32_t n_axes;
    uint32_t max_zones;
    uint32_t max_lines;
    /* The longest frame the board accepts, in encoded bytes including the
 delimiter. */
    uint32_t max_frame;
    uint32_t scan_hz;
    bool has_flashed;
    mousewheeld_link_v1_FlashedSet flashed;
} mousewheeld_link_v1_HelloAck;

/* The only high-rate message. Counts are cumulative, never deltas. */
typedef struct _mousewheeld_link_v1_Sample {
    /* Contiguous by construction: a jump is loss. */
    uint64_t seq;
    /* The device clock, free-running from boot. */
    uint64_t t_us;
    pb_size_t c_count;
    int64_t c[2];
    /* Counts per second over the board's window. Empty unless asked for. */
    pb_size_t v_count;
    int64_t v[2];
} mousewheeld_link_v1_Sample;

typedef struct _mousewheeld_link_v1_ZoneHit {
    /* Its own sequence, separate from `Sample.seq`. */
    uint64_t seq;
    uint32_t arm_id;
    /* The zone's index in the armed set. */
    uint32_t zone;
    uint64_t t_us;
    pb_size_t c_count;
    int64_t c[2];
} mousewheeld_link_v1_ZoneHit;

typedef struct _mousewheeld_link_v1_Armed {
    uint32_t arm_id;
    uint32_t zone_set_version;
} mousewheeld_link_v1_Armed;

typedef struct _mousewheeld_link_v1_StateReport {
    pb_size_t c_count;
    int64_t c[2];
    pb_size_t origin_count;
    int64_t origin[2];
    pb_size_t distance_count;
    int64_t distance[2];
    pb_size_t v_count;
    int64_t v[2];
    uint32_t n_axes;
    uint32_t stream_rate_hz;
    /* Present while a set is armed. */
    bool has_armed;
    mousewheeld_link_v1_Armed armed;
    /* Bit i set: zone i can still fire. */
    uint32_t zones_live;
    bool has_analog;
    mousewheeld_link_v1_Analog analog;
    /* Samples the ring had no room for. Visible as gaps in `Sample.seq`. */
    uint64_t ring_drops;
    uint64_t zone_hit_drops;
    /* Scans that started later than one and a half periods after the last. */
    uint64_t scan_overruns;
    uint32_t scan_max_us;
    /* Frames the board refused before reading them: CRC, COBS or length. */
    uint64_t frames_refused;
} mousewheeld_link_v1_StateReport;

/* `answers` names the command acknowledged. It is never `message_id`: every
 frame carries its own. */
typedef struct _mousewheeld_link_v1_Ok {
    uint32_t answers;
} mousewheeld_link_v1_Ok;

typedef struct _mousewheeld_link_v1_Error {
    char code[24];
    char detail[96];
    bool has_answers;
    uint32_t answers;
} mousewheeld_link_v1_Error;

typedef struct _mousewheeld_link_v1_Log {
    char text[120];
} mousewheeld_link_v1_Log;

typedef struct _mousewheeld_link_v1_Pong {
    uint32_t answers;
} mousewheeld_link_v1_Pong;

/* Everything the board sends is one of these. */
typedef struct _mousewheeld_link_v1_DeviceMessage {
    uint32_t message_id;
    pb_size_t which_body;
    union {
        mousewheeld_link_v1_HelloAck hello_ack;
        mousewheeld_link_v1_Sample sample;
        mousewheeld_link_v1_ZoneHit zone_hit;
        mousewheeld_link_v1_Armed armed;
        mousewheeld_link_v1_StateReport state_report;
        mousewheeld_link_v1_Ok ok;
        mousewheeld_link_v1_Error error;
        mousewheeld_link_v1_Log log;
        mousewheeld_link_v1_Pong pong;
    } body;
} mousewheeld_link_v1_DeviceMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _mousewheeld_link_v1_AxisSource_MIN mousewheeld_link_v1_AxisSource_AXIS_SOURCE_QUADRATURE
#define _mousewheeld_link_v1_AxisSource_MAX mousewheeld_link_v1_AxisSource_AXIS_SOURCE_OPTICAL_SPI
#define _mousewheeld_link_v1_AxisSource_ARRAYSIZE ((mousewheeld_link_v1_AxisSource)(mousewheeld_link_v1_AxisSource_AXIS_SOURCE_OPTICAL_SPI+1))

#define _mousewheeld_link_v1_Metric_MIN mousewheeld_link_v1_Metric_METRIC_DISPLACEMENT
#define _mousewheeld_link_v1_Metric_MAX mousewheeld_link_v1_Metric_METRIC_DISTANCE
#define _mousewheeld_link_v1_Metric_ARRAYSIZE ((mousewheeld_link_v1_Metric)(mousewheeld_link_v1_Metric_METRIC_DISTANCE+1))

#define _mousewheeld_link_v1_Fire_MIN mousewheeld_link_v1_Fire_FIRE_ONCE
#define _mousewheeld_link_v1_Fire_MAX mousewheeld_link_v1_Fire_FIRE_REARM
#define _mousewheeld_link_v1_Fire_ARRAYSIZE ((mousewheeld_link_v1_Fire)(mousewheeld_link_v1_Fire_FIRE_REARM+1))

#define _mousewheeld_link_v1_Action_MIN mousewheeld_link_v1_Action_ACTION_PULSE
#define _mousewheeld_link_v1_Action_MAX mousewheeld_link_v1_Action_ACTION_LEVEL
#define _mousewheeld_link_v1_Action_ARRAYSIZE ((mousewheeld_link_v1_Action)(mousewheeld_link_v1_Action_ACTION_LEVEL+1))

#define _mousewheeld_link_v1_Origin_MIN mousewheeld_link_v1_Origin_ORIGIN_CURRENT
#define _mousewheeld_link_v1_Origin_MAX mousewheeld_link_v1_Origin_ORIGIN_ABSOLUTE
#define _mousewheeld_link_v1_Origin_ARRAYSIZE ((mousewheeld_link_v1_Origin)(mousewheeld_link_v1_Origin_ORIGIN_ABSOLUTE+1))

#define _mousewheeld_link_v1_AnalogMode_MIN mousewheeld_link_v1_AnalogMode_ANALOG_MODE_OFF
#define _mousewheeld_link_v1_AnalogMode_MAX mousewheeld_link_v1_AnalogMode_ANALOG_MODE_VELOCITY
#define _mousewheeld_link_v1_AnalogMode_ARRAYSIZE ((mousewheeld_link_v1_AnalogMode)(mousewheeld_link_v1_AnalogMode_ANALOG_MODE_VELOCITY+1))




#define mousewheeld_link_v1_AxisConfig_source_ENUMTYPE mousewheeld_link_v1_AxisSource







#define mousewheeld_link_v1_Zone_metric_ENUMTYPE mousewheeld_link_v1_Metric
#define mousewheeld_link_v1_Zone_fire_ENUMTYPE mousewheeld_link_v1_Fire
#define mousewheeld_link_v1_Zone_action_ENUMTYPE mousewheeld_link_v1_Action


#define mousewheeld_link_v1_Arm_origin_ENUMTYPE mousewheeld_link_v1_Origin



#define mousewheeld_link_v1_Analog_mode_ENUMTYPE mousewheeld_link_v1_AnalogMode
















/* Initializer values for message structs */
#define mousewheeld_link_v1_HostMessage_init_default {0, 0, {mousewheeld_link_v1_Hello_init_default}}
#define mousewheeld_link_v1_DeviceMessage_init_default {0, 0, {mousewheeld_link_v1_HelloAck_init_default}}
#define mousewheeld_link_v1_Hello_init_default   {0}
#define mousewheeld_link_v1_AxisConfig_init_default {_mousewheeld_link_v1_AxisSource_MIN, 0}
#define mousewheeld_link_v1_Axes_init_default    {0, {mousewheeld_link_v1_AxisConfig_init_default, mousewheeld_link_v1_AxisConfig_init_default}}
#define mousewheeld_link_v1_Line_init_default    {0, 0, 0}
#define mousewheeld_link_v1_Lines_init_default   {0, {mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default, mousewheeld_link_v1_Line_init_default}}
#define mousewheeld_link_v1_Stream_init_default  {0, 0}
#define mousewheeld_link_v1_ZonesBegin_init_default {0, 0, ""}
#define mousewheeld_link_v1_Interval_init_default {0, false, 0, false, 0}
#define mousewheeld_link_v1_Zone_init_default    {0, 0, {mousewheeld_link_v1_Interval_init_default, mousewheeld_link_v1_Interval_init_default}, _mousewheeld_link_v1_Metric_MIN, 0, _mousewheeld_link_v1_Fire_MIN, 0, 0, 0, _mousewheeld_link_v1_Action_MIN, 0}
#define mousewheeld_link_v1_ZonesEnd_init_default {0}
#define mousewheeld_link_v1_Arm_init_default     {0, 0, _mousewheeld_link_v1_Origin_MIN}
#define mousewheeld_link_v1_Disarm_init_default  {0}
#define mousewheeld_link_v1_Zero_init_default    {0, {0, 0}}
#define mousewheeld_link_v1_Analog_init_default  {0, _mousewheeld_link_v1_AnalogMode_MIN, 0, 0, 0}
#define mousewheeld_link_v1_Save_init_default    {0}
#define mousewheeld_link_v1_Ping_init_default    {0}
#define mousewheeld_link_v1_StateRequest_init_default {0}
#define mousewheeld_link_v1_Debug_init_default   {0}
#define mousewheeld_link_v1_FlashedSet_init_default {"", 0}
#define mousewheeld_link_v1_HelloAck_init_default {"", "", 0, 0, 0, 0, 0, 0, false, mousewheeld_link_v1_FlashedSet_init_default}
#define mousewheeld_link_v1_Sample_init_default  {0, 0, 0, {0, 0}, 0, {0, 0}}
#define mousewheeld_link_v1_ZoneHit_init_default {0, 0, 0, 0, 0, {0, 0}}
#define mousewheeld_link_v1_Armed_init_default   {0, 0}
#define mousewheeld_link_v1_StateReport_init_default {0, {0, 0}, 0, {0, 0}, 0, {0, 0}, 0, {0, 0}, 0, 0, false, mousewheeld_link_v1_Armed_init_default, 0, false, mousewheeld_link_v1_Analog_init_default, 0, 0, 0, 0, 0}
#define mousewheeld_link_v1_Ok_init_default      {0}
#define mousewheeld_link_v1_Error_init_default   {"", "", false, 0}
#define mousewheeld_link_v1_Log_init_default     {""}
#define mousewheeld_link_v1_Pong_init_default    {0}
#define mousewheeld_link_v1_HostMessage_init_zero {0, 0, {mousewheeld_link_v1_Hello_init_zero}}
#define mousewheeld_link_v1_DeviceMessage_init_zero {0, 0, {mousewheeld_link_v1_HelloAck_init_zero}}
#define mousewheeld_link_v1_Hello_init_zero      {0}
#define mousewheeld_link_v1_AxisConfig_init_zero {_mousewheeld_link_v1_AxisSource_MIN, 0}
#define mousewheeld_link_v1_Axes_init_zero       {0, {mousewheeld_link_v1_AxisConfig_init_zero, mousewheeld_link_v1_AxisConfig_init_zero}}
#define mousewheeld_link_v1_Line_init_zero       {0, 0, 0}
#define mousewheeld_link_v1_Lines_init_zero      {0, {mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero, mousewheeld_link_v1_Line_init_zero}}
#define mousewheeld_link_v1_Stream_init_zero     {0, 0}
#define mousewheeld_link_v1_ZonesBegin_init_zero {0, 0, ""}
#define mousewheeld_link_v1_Interval_init_zero   {0, false, 0, false, 0}
#define mousewheeld_link_v1_Zone_init_zero       {0, 0, {mousewheeld_link_v1_Interval_init_zero, mousewheeld_link_v1_Interval_init_zero}, _mousewheeld_link_v1_Metric_MIN, 0, _mousewheeld_link_v1_Fire_MIN, 0, 0, 0, _mousewheeld_link_v1_Action_MIN, 0}
#define mousewheeld_link_v1_ZonesEnd_init_zero   {0}
#define mousewheeld_link_v1_Arm_init_zero        {0, 0, _mousewheeld_link_v1_Origin_MIN}
#define mousewheeld_link_v1_Disarm_init_zero     {0}
#define mousewheeld_link_v1_Zero_init_zero       {0, {0, 0}}
#define mousewheeld_link_v1_Analog_init_zero     {0, _mousewheeld_link_v1_AnalogMode_MIN, 0, 0, 0}
#define mousewheeld_link_v1_Save_init_zero       {0}
#define mousewheeld_link_v1_Ping_init_zero       {0}
#define mousewheeld_link_v1_StateRequest_init_zero {0}
#define mousewheeld_link_v1_Debug_init_zero      {0}
#define mousewheeld_link_v1_FlashedSet_init_zero {"", 0}
#define mousewheeld_link_v1_HelloAck_init_zero   {"", "", 0, 0, 0, 0, 0, 0, false, mousewheeld_link_v1_FlashedSet_init_zero}
#define mousewheeld_link_v1_Sample_init_zero     {0, 0, 0, {0, 0}, 0, {0, 0}}
#define mousewheeld_link_v1_ZoneHit_init_zero    {0, 0, 0, 0, 0, {0, 0}}
#define mousewheeld_link_v1_Armed_init_zero      {0, 0}
#define mousewheeld_link_v1_StateReport_init_zero {0, {0, 0}, 0, {0, 0}, 0, {0, 0}, 0, {0, 0}, 0, 0, false, mousewheeld_link_v1_Armed_init_zero, 0, false, mousewheeld_link_v1_Analog_init_zero, 0, 0, 0, 0, 0}
#define mousewheeld_link_v1_Ok_init_zero         {0}
#define mousewheeld_link_v1_Error_init_zero      {"", "", false, 0}
#define mousewheeld_link_v1_Log_init_zero        {""}
#define mousewheeld_link_v1_Pong_init_zero       {0}

/* Field tags (for use in manual encoding/decoding) */
#define mousewheeld_link_v1_Hello_protocol_version_tag 1
#define mousewheeld_link_v1_AxisConfig_source_tag 1
#define mousewheeld_link_v1_AxisConfig_invert_tag 2
#define mousewheeld_link_v1_Axes_axes_tag        1
#define mousewheeld_link_v1_Line_index_tag       1
#define mousewheeld_link_v1_Line_pin_tag         2
#define mousewheeld_link_v1_Line_safe_high_tag   3
#define mousewheeld_link_v1_Lines_lines_tag      1
#define mousewheeld_link_v1_Stream_rate_hz_tag   1
#define mousewheeld_link_v1_Stream_velocity_tag  2
#define mousewheeld_link_v1_ZonesBegin_zone_set_version_tag 1
#define mousewheeld_link_v1_ZonesBegin_n_tag     2
#define mousewheeld_link_v1_ZonesBegin_name_tag  3
#define mousewheeld_link_v1_Interval_axis_tag    1
#define mousewheeld_link_v1_Interval_lo_tag      2
#define mousewheeld_link_v1_Interval_hi_tag      3
#define mousewheeld_link_v1_Zone_index_tag       1
#define mousewheeld_link_v1_Zone_intervals_tag   2
#define mousewheeld_link_v1_Zone_metric_tag      3
#define mousewheeld_link_v1_Zone_wrap_tag        4
#define mousewheeld_link_v1_Zone_fire_tag        5
#define mousewheeld_link_v1_Zone_hysteresis_tag  6
#define mousewheeld_link_v1_Zone_level_on_arm_tag 7
#define mousewheeld_link_v1_Zone_line_tag        8
#define mousewheeld_link_v1_Zone_action_tag      9
#define mousewheeld_link_v1_Zone_pulse_ms_tag    10
#define mousewheeld_link_v1_Arm_arm_id_tag       1
#define mousewheeld_link_v1_Arm_zone_set_version_tag 2
#define mousewheeld_link_v1_Arm_origin_tag       3
#define mousewheeld_link_v1_Disarm_arm_id_tag    1
#define mousewheeld_link_v1_Zero_axes_tag        1
#define mousewheeld_link_v1_Analog_axis_tag      1
#define mousewheeld_link_v1_Analog_mode_tag      2
#define mousewheeld_link_v1_Analog_range_counts_tag 3
#define mousewheeld_link_v1_Analog_lo_tag        4
#define mousewheeld_link_v1_Analog_hi_tag        5
#define mousewheeld_link_v1_Debug_on_tag         1
#define mousewheeld_link_v1_HostMessage_message_id_tag 1
#define mousewheeld_link_v1_HostMessage_hello_tag 10
#define mousewheeld_link_v1_HostMessage_axes_tag 11
#define mousewheeld_link_v1_HostMessage_lines_tag 12
#define mousewheeld_link_v1_HostMessage_stream_tag 13
#define mousewheeld_link_v1_HostMessage_zones_begin_tag 14
#define mousewheeld_link_v1_HostMessage_zone_tag 15
#define mousewheeld_link_v1_HostMessage_zones_end_tag 16
#define mousewheeld_link_v1_HostMessage_arm_tag  17
#define mousewheeld_link_v1_HostMessage_disarm_tag 18
#define mousewheeld_link_v1_HostMessage_zero_tag 19
#define mousewheeld_link_v1_HostMessage_analog_tag 20
#define mousewheeld_link_v1_HostMessage_save_tag 21
#define mousewheeld_link_v1_HostMessage_ping_tag 22
#define mousewheeld_link_v1_HostMessage_state_tag 23
#define mousewheeld_link_v1_HostMessage_debug_tag 24
#define mousewheeld_link_v1_FlashedSet_name_tag  1
#define mousewheeld_link_v1_FlashedSet_version_tag 2
#define mousewheeld_link_v1_HelloAck_board_tag   1
#define mousewheeld_link_v1_HelloAck_firmware_tag 2
#define mousewheeld_link_v1_HelloAck_protocol_version_tag 3
#define mousewheeld_link_v1_HelloAck_n_axes_tag  4
#define mousewheeld_link_v1_HelloAck_max_zones_tag 5
#define mousewheeld_link_v1_HelloAck_max_lines_tag 6
#define mousewheeld_link_v1_HelloAck_max_frame_tag 7
#define mousewheeld_link_v1_HelloAck_scan_hz_tag 8
#define mousewheeld_link_v1_HelloAck_flashed_tag 9
#define mousewheeld_link_v1_Sample_seq_tag       1
#define mousewheeld_link_v1_Sample_t_us_tag      2
#define mousewheeld_link_v1_Sample_c_tag         3
#define mousewheeld_link_v1_Sample_v_tag         4
#define mousewheeld_link_v1_ZoneHit_seq_tag      1
#define mousewheeld_link_v1_ZoneHit_arm_id_tag   2
#define mousewheeld_link_v1_ZoneHit_zone_tag     3
#define mousewheeld_link_v1_ZoneHit_t_us_tag     4
#define mousewheeld_link_v1_ZoneHit_c_tag        5
#define mousewheeld_link_v1_Armed_arm_id_tag     1
#define mousewheeld_link_v1_Armed_zone_set_version_tag 2
#define mousewheeld_link_v1_StateReport_c_tag    1
#define mousewheeld_link_v1_StateReport_origin_tag 2
#define mousewheeld_link_v1_StateReport_distance_tag 3
#define mousewheeld_link_v1_StateReport_v_tag    4
#define mousewheeld_link_v1_StateReport_n_axes_tag 5
#define mousewheeld_link_v1_StateReport_stream_rate_hz_tag 6
#define mousewheeld_link_v1_StateReport_armed_tag 7
#define mousewheeld_link_v1_StateReport_zones_live_tag 8
#define mousewheeld_link_v1_StateReport_analog_tag 9
#define mousewheeld_link_v1_StateReport_ring_drops_tag 10
#define mousewheeld_link_v1_StateReport_zone_hit_drops_tag 11
#define mousewheeld_link_v1_StateReport_scan_overruns_tag 12
#define mousewheeld_link_v1_StateReport_scan_max_us_tag 13
#define mousewheeld_link_v1_StateReport_frames_refused_tag 14
#define mousewheeld_link_v1_Ok_answers_tag       1
#define mousewheeld_link_v1_Error_code_tag       1
#define mousewheeld_link_v1_Error_detail_tag     2
#define mousewheeld_link_v1_Error_answers_tag    3
#define mousewheeld_link_v1_Log_text_tag         1
#define mousewheeld_link_v1_Pong_answers_tag     1
#define mousewheeld_link_v1_DeviceMessage_message_id_tag 1
#define mousewheeld_link_v1_DeviceMessage_hello_ack_tag 10
#define mousewheeld_link_v1_DeviceMessage_sample_tag 11
#define mousewheeld_link_v1_DeviceMessage_zone_hit_tag 12
#define mousewheeld_link_v1_DeviceMessage_armed_tag 13
#define mousewheeld_link_v1_DeviceMessage_state_report_tag 14
#define mousewheeld_link_v1_DeviceMessage_ok_tag 15
#define mousewheeld_link_v1_DeviceMessage_error_tag 16
#define mousewheeld_link_v1_DeviceMessage_log_tag 17
#define mousewheeld_link_v1_DeviceMessage_pong_tag 18

/* Struct field encoding specification for nanopb */
#define mousewheeld_link_v1_HostMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello,body.hello),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,axes,body.axes),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,lines,body.lines),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,stream,body.stream),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,zones_begin,body.zones_begin),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,zone,body.zone),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,zones_end,body.zones_end),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,arm,body.arm),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,disarm,body.disarm),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,zero,body.zero),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,analog,body.analog),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,save,body.save),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ping,body.ping),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,state,body.state),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,debug,body.debug),  24)
#define mousewheeld_link_v1_HostMessage_CALLBACK NULL
#define mousewheeld_link_v1_HostMessage_DEFAULT NULL
#define mousewheeld_link_v1_HostMessage_body_hello_MSGTYPE mousewheeld_link_v1_Hello
#define mousewheeld_link_v1_HostMessage_body_axes_MSGTYPE mousewheeld_link_v1_Axes
#define mousewheeld_link_v1_HostMessage_body_lines_MSGTYPE mousewheeld_link_v1_Lines
#define mousewheeld_link_v1_HostMessage_body_stream_MSGTYPE mousewheeld_link_v1_Stream
#define mousewheeld_link_v1_HostMessage_body_zones_begin_MSGTYPE mousewheeld_link_v1_ZonesBegin
#define mousewheeld_link_v1_HostMessage_body_zone_MSGTYPE mousewheeld_link_v1_Zone
#define mousewheeld_link_v1_HostMessage_body_zones_end_MSGTYPE mousewheeld_link_v1_ZonesEnd
#define mousewheeld_link_v1_HostMessage_body_arm_MSGTYPE mousewheeld_link_v1_Arm
#define mousewheeld_link_v1_HostMessage_body_disarm_MSGTYPE mousewheeld_link_v1_Disarm
#define mousewheeld_link_v1_HostMessage_body_zero_MSGTYPE mousewheeld_link_v1_Zero
#define mousewheeld_link_v1_HostMessage_body_analog_MSGTYPE mousewheeld_link_v1_Analog
#define mousewheeld_link_v1_HostMessage_body_save_MSGTYPE mousewheeld_link_v1_Save
#define mousewheeld_link_v1_HostMessage_body_ping_MSGTYPE mousewheeld_link_v1_Ping
#define mousewheeld_link_v1_HostMessage_body_state_MSGTYPE mousewheeld_link_v1_StateRequest
#define mousewheeld_link_v1_HostMessage_body_debug_MSGTYPE mousewheeld_link_v1_Debug

#define mousewheeld_link_v1_DeviceMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello_ack,body.hello_ack),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,sample,body.sample),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,zone_hit,body.zone_hit),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,armed,body.armed),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,state_report,body.state_report),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ok,body.ok),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,error,body.error),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,log,body.log),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pong,body.pong),  18)
#define mousewheeld_link_v1_DeviceMessage_CALLBACK NULL
#define mousewheeld_link_v1_DeviceMessage_DEFAULT NULL
#define mousewheeld_link_v1_DeviceMessage_body_hello_ack_MSGTYPE mousewheeld_link_v1_HelloAck
#define mousewheeld_link_v1_DeviceMessage_body_sample_MSGTYPE mousewheeld_link_v1_Sample
#define mousewheeld_link_v1_DeviceMessage_body_zone_hit_MSGTYPE mousewheeld_link_v1_ZoneHit
#define mousewheeld_link_v1_DeviceMessage_body_armed_MSGTYPE mousewheeld_link_v1_Armed
#define mousewheeld_link_v1_DeviceMessage_body_state_report_MSGTYPE mousewheeld_link_v1_StateReport
#define mousewheeld_link_v1_DeviceMessage_body_ok_MSGTYPE mousewheeld_link_v1_Ok
#define mousewheeld_link_v1_DeviceMessage_body_error_MSGTYPE mousewheeld_link_v1_Error
#define mousewheeld_link_v1_DeviceMessage_body_log_MSGTYPE mousewheeld_link_v1_Log
#define mousewheeld_link_v1_DeviceMessage_body_pong_MSGTYPE mousewheeld_link_v1_Pong

#define mousewheeld_link_v1_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1)
#define mousewheeld_link_v1_Hello_CALLBACK NULL
#define mousewheeld_link_v1_Hello_DEFAULT NULL

#define mousewheeld_link_v1_AxisConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    source,            1) \
X(a, STATIC,   SINGULAR, BOOL,     invert,            2)
#define mousewheeld_link_v1_AxisConfig_CALLBACK NULL
#define mousewheeld_link_v1_AxisConfig_DEFAULT NULL

#define mousewheeld_link_v1_Axes_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  axes,              1)
#define mousewheeld_link_v1_Axes_CALLBACK NULL
#define mousewheeld_link_v1_Axes_DEFAULT NULL
#define mousewheeld_link_v1_Axes_axes_MSGTYPE mousewheeld_link_v1_AxisConfig

#define mousewheeld_link_v1_Line_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               2) \
X(a, STATIC,   SINGULAR, BOOL,     safe_high,         3)
#define mousewheeld_link_v1_Line_CALLBACK NULL
#define mousewheeld_link_v1_Line_DEFAULT NULL

#define mousewheeld_link_v1_Lines_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  lines,             1)
#define mousewheeld_link_v1_Lines_CALLBACK NULL
#define mousewheeld_link_v1_Lines_DEFAULT NULL
#define mousewheeld_link_v1_Lines_lines_MSGTYPE mousewheeld_link_v1_Line

#define mousewheeld_link_v1_Stream_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           1) \
X(a, STATIC,   SINGULAR, BOOL,     velocity,          2)
#define mousewheeld_link_v1_Stream_CALLBACK NULL
#define mousewheeld_link_v1_Stream_DEFAULT NULL

#define mousewheeld_link_v1_ZonesBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   zone_set_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   n,                 2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3)
#define mousewheeld_link_v1_ZonesBegin_CALLBACK NULL
#define mousewheeld_link_v1_ZonesBegin_DEFAULT NULL

#define mousewheeld_link_v1_Interval_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   axis,              1) \
X(a, STATIC,   OPTIONAL, SINT64,   lo,                2) \
X(a, STATIC,   OPTIONAL, SINT64,   hi,                3)
#define mousewheeld_link_v1_Interval_CALLBACK NULL
#define mousewheeld_link_v1_Interval_DEFAULT NULL

#define mousewheeld_link_v1_Zone_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   REPEATED, MESSAGE,  intervals,         2) \
X(a, STATIC,   SINGULAR, UENUM,    metric,            3) \
X(a, STATIC,   SINGULAR, SINT64,   wrap,              4) \
X(a, STATIC,   SINGULAR, UENUM,    fire,              5) \
X(a, STATIC,   SINGULAR, SINT64,   hysteresis,        6) \
X(a, STATIC,   SINGULAR, BOOL,     level_on_arm,      7) \
X(a, STATIC,   SINGULAR, UINT32,   line,              8) \
X(a, STATIC,   SINGULAR, UENUM,    action,            9) \
X(a, STATIC,   SINGULAR, UINT32,   pulse_ms,         10)
#define mousewheeld_link_v1_Zone_CALLBACK NULL
#define mousewheeld_link_v1_Zone_DEFAULT NULL
#define mousewheeld_link_v1_Zone_intervals_MSGTYPE mousewheeld_link_v1_Interval

#define mousewheeld_link_v1_ZonesEnd_FIELDLIST(X, a) \

#define mousewheeld_link_v1_ZonesEnd_CALLBACK NULL
#define mousewheeld_link_v1_ZonesEnd_DEFAULT NULL

#define mousewheeld_link_v1_Arm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   arm_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   zone_set_version,   2) \
X(a, STATIC,   SINGULAR, UENUM,    origin,            3)
#define mousewheeld_link_v1_Arm_CALLBACK NULL
#define mousewheeld_link_v1_Arm_DEFAULT NULL

#define mousewheeld_link_v1_Disarm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   arm_id,            1)
#define mousewheeld_link_v1_Disarm_CALLBACK NULL
#define mousewheeld_link_v1_Disarm_DEFAULT NULL

#define mousewheeld_link_v1_Zero_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   axes,              1)
#define mousewheeld_link_v1_Zero_CALLBACK NULL
#define mousewheeld_link_v1_Zero_DEFAULT NULL

#define mousewheeld_link_v1_Analog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   axis,              1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   SINGULAR, SINT64,   range_counts,      3) \
X(a, STATIC,   SINGULAR, SINT64,   lo,                4) \
X(a, STATIC,   SINGULAR, SINT64,   hi,                5)
#define mousewheeld_link_v1_Analog_CALLBACK NULL
#define mousewheeld_link_v1_Analog_DEFAULT NULL

#define mousewheeld_link_v1_Save_FIELDLIST(X, a) \

#define mousewheeld_link_v1_Save_CALLBACK NULL
#define mousewheeld_link_v1_Save_DEFAULT NULL

#define mousewheeld_link_v1_Ping_FIELDLIST(X, a) \

#define mousewheeld_link_v1_Ping_CALLBACK NULL
#define mousewheeld_link_v1_Ping_DEFAULT NULL

#define mousewheeld_link_v1_StateRequest_FIELDLIST(X, a) \

#define mousewheeld_link_v1_StateRequest_CALLBACK NULL
#define mousewheeld_link_v1_StateRequest_DEFAULT NULL

#define mousewheeld_link_v1_Debug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1)
#define mousewheeld_link_v1_Debug_CALLBACK NULL
#define mousewheeld_link_v1_Debug_DEFAULT NULL

#define mousewheeld_link_v1_FlashedSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   version,           2)
#define mousewheeld_link_v1_FlashedSet_CALLBACK NULL
#define mousewheeld_link_v1_FlashedSet_DEFAULT NULL

#define mousewheeld_link_v1_HelloAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   board,             1) \
X(a, STATIC,   SINGULAR, STRING,   firmware,          2) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   3) \
X(a, STATIC,   SINGULAR, UINT32,   n_axes,            4) \
X(a, STATIC,   SINGULAR, UINT32,   max_zones,         5) \
X(a, STATIC,   SINGULAR, UINT32,   max_lines,         6) \
X(a, STATIC,   SINGULAR, UINT32,   max_frame,         7) \
X(a, STATIC,   SINGULAR, UINT32,   scan_hz,           8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  flashed,           9)
#define mousewheeld_link_v1_HelloAck_CALLBACK NULL
#define mousewheeld_link_v1_HelloAck_DEFAULT NULL
#define mousewheeld_link_v1_HelloAck_flashed_MSGTYPE mousewheeld_link_v1_FlashedSet

#define mousewheeld_link_v1_Sample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT64,   t_us,              2) \
X(a, STATIC,   REPEATED, SINT64,   c,                 3) \
X(a, STATIC,   REPEATED, SINT64,   v,                 4)
#define mousewheeld_link_v1_Sample_CALLBACK NULL
#define mousewheeld_link_v1_Sample_DEFAULT NULL

#define mousewheeld_link_v1_ZoneHit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT32,   arm_id,            2) \
X(a, STATIC,   SINGULAR, UINT32,   zone,              3) \
X(a, STATIC,   SINGULAR, UINT64,   t_us,              4) \
X(a, STATIC,   REPEATED, SINT64,   c,                 5)
#define mousewheeld_link_v1_ZoneHit_CALLBACK NULL
#define mousewheeld_link_v1_ZoneHit_DEFAULT NULL

#define mousewheeld_link_v1_Armed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   arm_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   zone_set_version,   2)
#define mousewheeld_link_v1_Armed_CALLBACK NULL
#define mousewheeld_link_v1_Armed_DEFAULT NULL

#define mousewheeld_link_v1_StateReport_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, SINT64,   c,                 1) \
X(a, STATIC,   REPEATED, SINT64,   origin,            2) \
X(a, STATIC,   REPEATED, SINT64,   distance,          3) \
X(a, STATIC,   REPEATED, SINT64,   v,                 4) \
X(a, STATIC,   SINGULAR, UINT32,   n_axes,            5) \
X(a, STATIC,   SINGULAR, UINT32,   stream_rate_hz,    6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  armed,             7) \
X(a, STATIC,   SINGULAR, UINT32,   zones_live,        8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  analog,            9) \
X(a, STATIC,   SINGULAR, UINT64,   ring_drops,       10) \
X(a, STATIC,   SINGULAR, UINT64,   zone_hit_drops,   11) \
X(a, STATIC,   SINGULAR, UINT64,   scan_overruns,    12) \
X(a, STATIC,   SINGULAR, UINT32,   scan_max_us,      13) \
X(a, STATIC,   SINGULAR, UINT64,   frames_refused,   14)
#define mousewheeld_link_v1_StateReport_CALLBACK NULL
#define mousewheeld_link_v1_StateReport_DEFAULT NULL
#define mousewheeld_link_v1_StateReport_armed_MSGTYPE mousewheeld_link_v1_Armed
#define mousewheeld_link_v1_StateReport_analog_MSGTYPE mousewheeld_link_v1_Analog

#define mousewheeld_link_v1_Ok_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   answers,           1)
#define mousewheeld_link_v1_Ok_CALLBACK NULL
#define mousewheeld_link_v1_Ok_DEFAULT NULL

#define mousewheeld_link_v1_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   code,              1) \
X(a, STATIC,   SINGULAR, STRING,   detail,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   answers,           3)
#define mousewheeld_link_v1_Error_CALLBACK NULL
#define mousewheeld_link_v1_Error_DEFAULT NULL

#define mousewheeld_link_v1_Log_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define mousewheeld_link_v1_Log_CALLBACK NULL
#define mousewheeld_link_v1_Log_DEFAULT NULL

#define mousewheeld_link_v1_Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   answers,           1)
#define mousewheeld_link_v1_Pong_CALLBACK NULL
#define mousewheeld_link_v1_Pong_DEFAULT NULL

extern const pb_msgdesc_t mousewheeld_link_v1_HostMessage_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_DeviceMessage_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Hello_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_AxisConfig_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Axes_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Line_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Lines_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Stream_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_ZonesBegin_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Interval_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Zone_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_ZonesEnd_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Arm_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Disarm_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Zero_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Analog_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Save_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Ping_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_StateRequest_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Debug_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_FlashedSet_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_HelloAck_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Sample_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_ZoneHit_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Armed_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_StateReport_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Ok_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Error_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Log_msg;
extern const pb_msgdesc_t mousewheeld_link_v1_Pong_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define mousewheeld_link_v1_HostMessage_fields &mousewheeld_link_v1_HostMessage_msg
#define mousewheeld_link_v1_DeviceMessage_fields &mousewheeld_link_v1_DeviceMessage_msg
#define mousewheeld_link_v1_Hello_fields &mousewheeld_link_v1_Hello_msg
#define mousewheeld_link_v1_AxisConfig_fields &mousewheeld_link_v1_AxisConfig_msg
#define mousewheeld_link_v1_Axes_fields &mousewheeld_link_v1_Axes_msg
#define mousewheeld_link_v1_Line_fields &mousewheeld_link_v1_Line_msg
#define mousewheeld_link_v1_Lines_fields &mousewheeld_link_v1_Lines_msg
#define mousewheeld_link_v1_Stream_fields &mousewheeld_link_v1_Stream_msg
#define mousewheeld_link_v1_ZonesBegin_fields &mousewheeld_link_v1_ZonesBegin_msg
#define mousewheeld_link_v1_Interval_fields &mousewheeld_link_v1_Interval_msg
#define mousewheeld_link_v1_Zone_fields &mousewheeld_link_v1_Zone_msg
#define mousewheeld_link_v1_ZonesEnd_fields &mousewheeld_link_v1_ZonesEnd_msg
#define mousewheeld_link_v1_Arm_fields &mousewheeld_link_v1_Arm_msg
#define mousewheeld_link_v1_Disarm_fields &mousewheeld_link_v1_Disarm_msg
#define mousewheeld_link_v1_Zero_fields &mousewheeld_link_v1_Zero_msg
#define mousewheeld_link_v1_Analog_fields &mousewheeld_link_v1_Analog_msg
#define mousewheeld_link_v1_Save_fields &mousewheeld_link_v1_Save_msg
#define mousewheeld_link_v1_Ping_fields &mousewheeld_link_v1_Ping_msg
#define mousewheeld_link_v1_StateRequest_fields &mousewheeld_link_v1_StateRequest_msg
#define mousewheeld_link_v1_Debug_fields &mousewheeld_link_v1_Debug_msg
#define mousewheeld_link_v1_FlashedSet_fields &mousewheeld_link_v1_FlashedSet_msg
#define mousewheeld_link_v1_HelloAck_fields &mousewheeld_link_v1_HelloAck_msg
#define mousewheeld_link_v1_Sample_fields &mousewheeld_link_v1_Sample_msg
#define mousewheeld_link_v1_ZoneHit_fields &mousewheeld_link_v1_ZoneHit_msg
#define mousewheeld_link_v1_Armed_fields &mousewheeld_link_v1_Armed_msg
#define mousewheeld_link_v1_StateReport_fields &mousewheeld_link_v1_StateReport_msg
#define mousewheeld_link_v1_Ok_fields &mousewheeld_link_v1_Ok_msg
#define mousewheeld_link_v1_Error_fields &mousewheeld_link_v1_Error_msg
#define mousewheeld_link_v1_Log_fields &mousewheeld_link_v1_Log_msg
#define mousewheeld_link_v1_Pong_fields &mousewheeld_link_v1_Pong_msg

/* Maximum encoded size of messages (where known) */
#define MOUSEWHEELD_LINK_V1_MOUSEWHEELD_LINK_V1_LINK_PB_H_MAX_SIZE mousewheeld_link_v1_DeviceMessage_size
#define mousewheeld_link_v1_Analog_size          41
#define mousewheeld_link_v1_Arm_size             14
#define mousewheeld_link_v1_Armed_size           12
#define mousewheeld_link_v1_Axes_size            12
#define mousewheeld_link_v1_AxisConfig_size      4
#define mousewheeld_link_v1_Debug_size           2
#define mousewheeld_link_v1_DeviceMessage_size   222
#define mousewheeld_link_v1_Disarm_size          6
#define mousewheeld_link_v1_Error_size           128
#define mousewheeld_link_v1_FlashedSet_size      40
#define mousewheeld_link_v1_HelloAck_size        136
#define mousewheeld_link_v1_Hello_size           6
#define mousewheeld_link_v1_HostMessage_size     137
#define mousewheeld_link_v1_Interval_size        28
#define mousewheeld_link_v1_Line_size            14
#define mousewheeld_link_v1_Lines_size           128
#define mousewheeld_link_v1_Log_size             121
#define mousewheeld_link_v1_Ok_size              6
#define mousewheeld_link_v1_Ping_size            0
#define mousewheeld_link_v1_Pong_size            6
#define mousewheeld_link_v1_Sample_size          66
#define mousewheeld_link_v1_Save_size            0
#define mousewheeld_link_v1_StateReport_size     213
#define mousewheeld_link_v1_StateRequest_size    0
#define mousewheeld_link_v1_Stream_size          8
#define mousewheeld_link_v1_Zero_size            12
#define mousewheeld_link_v1_ZoneHit_size         56
#define mousewheeld_link_v1_Zone_size            108
#define mousewheeld_link_v1_ZonesBegin_size      46
#define mousewheeld_link_v1_ZonesEnd_size        0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
