/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mousewheeld/link/v1/link.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mousewheeld_link_v1_HostMessage, mousewheeld_link_v1_HostMessage, AUTO)


PB_BIND(mousewheeld_link_v1_DeviceMessage, mousewheeld_link_v1_DeviceMessage, AUTO)


PB_BIND(mousewheeld_link_v1_Hello, mousewheeld_link_v1_Hello, AUTO)


PB_BIND(mousewheeld_link_v1_AxisConfig, mousewheeld_link_v1_AxisConfig, AUTO)


PB_BIND(mousewheeld_link_v1_Axes, mousewheeld_link_v1_Axes, AUTO)


PB_BIND(mousewheeld_link_v1_Line, mousewheeld_link_v1_Line, AUTO)


PB_BIND(mousewheeld_link_v1_Lines, mousewheeld_link_v1_Lines, AUTO)


PB_BIND(mousewheeld_link_v1_Stream, mousewheeld_link_v1_Stream, AUTO)


PB_BIND(mousewheeld_link_v1_ZonesBegin, mousewheeld_link_v1_ZonesBegin, AUTO)


PB_BIND(mousewheeld_link_v1_Interval, mousewheeld_link_v1_Interval, AUTO)


PB_BIND(mousewheeld_link_v1_Zone, mousewheeld_link_v1_Zone, AUTO)


PB_BIND(mousewheeld_link_v1_ZonesEnd, mousewheeld_link_v1_ZonesEnd, AUTO)


PB_BIND(mousewheeld_link_v1_Arm, mousewheeld_link_v1_Arm, AUTO)


PB_BIND(mousewheeld_link_v1_Disarm, mousewheeld_link_v1_Disarm, AUTO)


PB_BIND(mousewheeld_link_v1_Zero, mousewheeld_link_v1_Zero, AUTO)


PB_BIND(mousewheeld_link_v1_Analog, mousewheeld_link_v1_Analog, AUTO)


PB_BIND(mousewheeld_link_v1_Save, mousewheeld_link_v1_Save, AUTO)


PB_BIND(mousewheeld_link_v1_Ping, mousewheeld_link_v1_Ping, AUTO)


PB_BIND(mousewheeld_link_v1_StateRequest, mousewheeld_link_v1_StateRequest, AUTO)


PB_BIND(mousewheeld_link_v1_Debug, mousewheeld_link_v1_Debug, AUTO)


PB_BIND(mousewheeld_link_v1_FlashedSet, mousewheeld_link_v1_FlashedSet, AUTO)


PB_BIND(mousewheeld_link_v1_HelloAck, mousewheeld_link_v1_HelloAck, AUTO)


PB_BIND(mousewheeld_link_v1_Sample, mousewheeld_link_v1_Sample, AUTO)


PB_BIND(mousewheeld_link_v1_ZoneHit, mousewheeld_link_v1_ZoneHit, AUTO)


PB_BIND(mousewheeld_link_v1_Armed, mousewheeld_link_v1_Armed, AUTO)


PB_BIND(mousewheeld_link_v1_StateReport, mousewheeld_link_v1_StateReport, AUTO)


PB_BIND(mousewheeld_link_v1_Ok, mousewheeld_link_v1_Ok, AUTO)


PB_BIND(mousewheeld_link_v1_Error, mousewheeld_link_v1_Error, AUTO)


PB_BIND(mousewheeld_link_v1_Log, mousewheeld_link_v1_Log, AUTO)


PB_BIND(mousewheeld_link_v1_Pong, mousewheeld_link_v1_Pong, AUTO)















