// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generates the browser's protobuf types from `proto/` and bundles the network
// module the panels import.
//
// **The bundle is committed**, for the same reason `daemon/src/wire/` is: a
// checkout builds with cargo alone. `rust-embed` reads `elements/` at compile
// time, so anything generated here has to exist before `cargo build` — and a
// daemon whose release build needs npm on the machine is a daemon that cannot
// be built on the rig. `make web` runs this; `make check-web` fails if what is
// committed is not what it produces.
//
// Only this one file is bundled. The panels stay hand-written ES modules served
// as themselves, so `make dev` still means edit-and-reload.

import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const protoRoot = join(here, "../../proto");
const generated = join(here, "gen");
const bundle = join(here, "elements/daemon_api_client.js");

rmSync(generated, { recursive: true, force: true });
mkdirSync(generated, { recursive: true });

execFileSync(
  "protoc",
  [
    `--proto_path=${protoRoot}`,
    `--plugin=protoc-gen-es=${join(here, "node_modules/.bin/protoc-gen-es")}`,
    `--es_out=${generated}`,
    "--es_opt=target=js,import_extension=js",
    ...["calibration", "config", "device", "error", "state", "version", "zones"].map(
      (file) => `${protoRoot}/mousewheeld/v1/${file}.proto`,
    ),
  ],
  { stdio: "inherit" },
);

await esbuild.build({
  entryPoints: [join(here, "src/daemon_api_client.js")],
  outfile: bundle,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  // Not minified, deliberately. A committed artifact nobody can read is a
  // committed artifact nobody reviews, and `make check-web` diffs this file.
  minify: false,
  legalComments: "none",
});

// The banner goes on afterwards so esbuild's own output is the only thing the
// staleness check compares, and so the first line of the file says what it is.
const banner = `// SPDX-License-Identifier: AGPL-3.0-or-later
//
// @generated by client/web/build_daemon_api_client.mjs — run \`make web\`, do not edit.
//
// The source is client/web/src/daemon_api_client.js; the protobuf types are
// generated from proto/mousewheeld/v1/; the rest is @bufbuild/protobuf and
// @connectrpc/connect-web, bundled so that a checkout needs no npm to build.
`;
writeFileSync(bundle, banner + readFileSync(bundle, "utf8"));

console.log(`elements/daemon_api_client.js — ${(readFileSync(bundle).length / 1024).toFixed(0)} KiB`);
