// This file is @generated by prost-build.
/// Everything the daemon sends is one of these.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostMessage {
    /// The sender's per-direction counter, wrapping at 16 bits. For link-level
    /// retry and nothing else — it is not `seq`.
    #[prost(uint32, tag = "1")]
    pub message_id: u32,
    #[prost(
        oneof = "host_message::Body",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24"
    )]
    pub body: ::core::option::Option<host_message::Body>,
}
/// Nested message and enum types in `HostMessage`.
pub mod host_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "10")]
        Hello(super::Hello),
        #[prost(message, tag = "11")]
        Axes(super::Axes),
        #[prost(message, tag = "12")]
        Lines(super::Lines),
        #[prost(message, tag = "13")]
        Stream(super::Stream),
        #[prost(message, tag = "14")]
        ZonesBegin(super::ZonesBegin),
        #[prost(message, tag = "15")]
        Zone(super::Zone),
        #[prost(message, tag = "16")]
        ZonesEnd(super::ZonesEnd),
        #[prost(message, tag = "17")]
        Arm(super::Arm),
        #[prost(message, tag = "18")]
        Disarm(super::Disarm),
        #[prost(message, tag = "19")]
        Zero(super::Zero),
        #[prost(message, tag = "20")]
        Analog(super::Analog),
        #[prost(message, tag = "21")]
        Save(super::Save),
        #[prost(message, tag = "22")]
        Ping(super::Ping),
        #[prost(message, tag = "23")]
        State(super::StateRequest),
        #[prost(message, tag = "24")]
        Debug(super::Debug),
    }
}
/// Everything the board sends is one of these.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceMessage {
    #[prost(uint32, tag = "1")]
    pub message_id: u32,
    #[prost(oneof = "device_message::Body", tags = "10, 11, 12, 13, 14, 15, 16, 17, 18")]
    pub body: ::core::option::Option<device_message::Body>,
}
/// Nested message and enum types in `DeviceMessage`.
pub mod device_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "10")]
        HelloAck(super::HelloAck),
        #[prost(message, tag = "11")]
        Sample(super::Sample),
        #[prost(message, tag = "12")]
        ZoneHit(super::ZoneHit),
        #[prost(message, tag = "13")]
        Armed(super::Armed),
        #[prost(message, tag = "14")]
        StateReport(super::StateReport),
        #[prost(message, tag = "15")]
        Ok(super::Ok),
        #[prost(message, tag = "16")]
        Error(super::Error),
        #[prost(message, tag = "17")]
        Log(super::Log),
        #[prost(message, tag = "18")]
        Pong(super::Pong),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AxisConfig {
    #[prost(enumeration = "AxisSource", tag = "1")]
    pub source: i32,
    #[prost(bool, tag = "2")]
    pub invert: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Axes {
    #[prost(message, repeated, tag = "1")]
    pub axes: ::prost::alloc::vec::Vec<AxisConfig>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Line {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub pin: u32,
    /// The idle level. A line is *active* at the other one.
    #[prost(bool, tag = "3")]
    pub safe_high: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Lines {
    #[prost(message, repeated, tag = "1")]
    pub lines: ::prost::alloc::vec::Vec<Line>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Stream {
    /// Samples per second; 0 stops the stream. At most the board's `scan_hz`.
    #[prost(uint32, tag = "1")]
    pub rate_hz: u32,
    /// Carry the device's own velocity on each sample.
    #[prost(bool, tag = "2")]
    pub velocity: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZonesBegin {
    #[prost(uint32, tag = "1")]
    pub zone_set_version: u32,
    /// How many `Zone`s follow. `ZonesEnd` is refused unless every index in
    /// `0..n` arrived.
    #[prost(uint32, tag = "2")]
    pub n: u32,
    /// The one string the board stores: `HelloAck.flashed` reports a flashed
    /// set by it.
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
/// One axis of a rect: an interval in counts. An absent bound is open.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Interval {
    #[prost(uint32, tag = "1")]
    pub axis: u32,
    #[prost(sint64, optional, tag = "2")]
    pub lo: ::core::option::Option<i64>,
    #[prost(sint64, optional, tag = "3")]
    pub hi: ::core::option::Option<i64>,
}
/// One compiled zone: integer counts, no names, no units.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Zone {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(message, repeated, tag = "2")]
    pub intervals: ::prost::alloc::vec::Vec<Interval>,
    #[prost(enumeration = "Metric", tag = "3")]
    pub metric: i32,
    /// Period in counts; 0 for a straight track.
    #[prost(sint64, tag = "4")]
    pub wrap: i64,
    #[prost(enumeration = "Fire", tag = "5")]
    pub fire: i32,
    #[prost(sint64, tag = "6")]
    pub hysteresis: i64,
    /// Fire on arming if already inside.
    #[prost(bool, tag = "7")]
    pub level_on_arm: bool,
    #[prost(uint32, tag = "8")]
    pub line: u32,
    #[prost(enumeration = "Action", tag = "9")]
    pub action: i32,
    #[prost(uint32, tag = "10")]
    pub pulse_ms: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZonesEnd {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Arm {
    #[prost(uint32, tag = "1")]
    pub arm_id: u32,
    /// Must be the committed set's. A mismatch is refused, so a board that lost
    /// an upload never arms the set before it.
    #[prost(uint32, tag = "2")]
    pub zone_set_version: u32,
    #[prost(enumeration = "Origin", tag = "3")]
    pub origin: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Disarm {
    #[prost(uint32, tag = "1")]
    pub arm_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Zero {
    /// Axis indices; empty for all.
    #[prost(uint32, repeated, tag = "1")]
    pub axes: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Analog {
    #[prost(uint32, tag = "1")]
    pub axis: u32,
    #[prost(enumeration = "AnalogMode", tag = "2")]
    pub mode: i32,
    #[prost(sint64, tag = "3")]
    pub range_counts: i64,
    #[prost(sint64, tag = "4")]
    pub lo: i64,
    #[prost(sint64, tag = "5")]
    pub hi: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Save {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateRequest {}
/// Human-readable text on the serial port, for a terminal. Left by `Hello`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Debug {
    #[prost(bool, tag = "1")]
    pub on: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlashedSet {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub version: u32,
}
/// Sent in reply to `Hello`, and unasked at boot — which is how the daemon
/// learns the board reset.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HelloAck {
    #[prost(string, tag = "1")]
    pub board: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub firmware: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub protocol_version: u32,
    #[prost(uint32, tag = "4")]
    pub n_axes: u32,
    #[prost(uint32, tag = "5")]
    pub max_zones: u32,
    #[prost(uint32, tag = "6")]
    pub max_lines: u32,
    /// The longest frame the board accepts, in encoded bytes including the
    /// delimiter.
    #[prost(uint32, tag = "7")]
    pub max_frame: u32,
    #[prost(uint32, tag = "8")]
    pub scan_hz: u32,
    #[prost(message, optional, tag = "9")]
    pub flashed: ::core::option::Option<FlashedSet>,
}
/// The only high-rate message. Counts are cumulative, never deltas.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Sample {
    /// Contiguous by construction: a jump is loss.
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    /// The device clock, free-running from boot.
    #[prost(uint64, tag = "2")]
    pub t_us: u64,
    #[prost(sint64, repeated, tag = "3")]
    pub c: ::prost::alloc::vec::Vec<i64>,
    /// Counts per second over the board's window. Empty unless asked for.
    #[prost(sint64, repeated, tag = "4")]
    pub v: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZoneHit {
    /// Its own sequence, separate from `Sample.seq`.
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    #[prost(uint32, tag = "2")]
    pub arm_id: u32,
    /// The zone's index in the armed set.
    #[prost(uint32, tag = "3")]
    pub zone: u32,
    #[prost(uint64, tag = "4")]
    pub t_us: u64,
    #[prost(sint64, repeated, tag = "5")]
    pub c: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Armed {
    #[prost(uint32, tag = "1")]
    pub arm_id: u32,
    #[prost(uint32, tag = "2")]
    pub zone_set_version: u32,
    /// Per axis, the origin the board is evaluating against, in its own raw
    /// counts. With `ORIGIN_CURRENT` it was set when the board read the Arm,
    /// which is later than any sample the host has: the host adopts this rather
    /// than guessing, or every position it reports for the set is off by the
    /// stream's lag.
    #[prost(sint64, repeated, tag = "3")]
    pub origin: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateReport {
    #[prost(sint64, repeated, tag = "1")]
    pub c: ::prost::alloc::vec::Vec<i64>,
    #[prost(sint64, repeated, tag = "2")]
    pub origin: ::prost::alloc::vec::Vec<i64>,
    #[prost(sint64, repeated, tag = "3")]
    pub distance: ::prost::alloc::vec::Vec<i64>,
    #[prost(sint64, repeated, tag = "4")]
    pub v: ::prost::alloc::vec::Vec<i64>,
    #[prost(uint32, tag = "5")]
    pub n_axes: u32,
    #[prost(uint32, tag = "6")]
    pub stream_rate_hz: u32,
    /// Present while a set is armed.
    #[prost(message, optional, tag = "7")]
    pub armed: ::core::option::Option<Armed>,
    /// Bit i set: zone i can still fire.
    #[prost(uint32, tag = "8")]
    pub zones_live: u32,
    #[prost(message, optional, tag = "9")]
    pub analog: ::core::option::Option<Analog>,
    /// Samples the ring had no room for. Visible as gaps in `Sample.seq`.
    #[prost(uint64, tag = "10")]
    pub ring_drops: u64,
    #[prost(uint64, tag = "11")]
    pub zone_hit_drops: u64,
    /// Scans that started later than one and a half periods after the last.
    #[prost(uint64, tag = "12")]
    pub scan_overruns: u64,
    #[prost(uint32, tag = "13")]
    pub scan_max_us: u32,
    /// Frames the board refused before reading them: CRC, COBS or length.
    #[prost(uint64, tag = "14")]
    pub frames_refused: u64,
}
/// `answers` names the command acknowledged. It is never `message_id`: every
/// frame carries its own.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ok {
    #[prost(uint32, tag = "1")]
    pub answers: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "3")]
    pub answers: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Log {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pong {
    #[prost(uint32, tag = "1")]
    pub answers: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AxisSource {
    Quadrature = 0,
    /// Declared so the model is N-axis from day one; refused by name as
    /// `unsupported_source` until a board can read one.
    OpticalSpi = 1,
}
impl AxisSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Quadrature => "AXIS_SOURCE_QUADRATURE",
            Self::OpticalSpi => "AXIS_SOURCE_OPTICAL_SPI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AXIS_SOURCE_QUADRATURE" => Some(Self::Quadrature),
            "AXIS_SOURCE_OPTICAL_SPI" => Some(Self::OpticalSpi),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Metric {
    /// counts − origin, signed
    Displacement = 0,
    /// Σ|Δcounts| since the origin was set
    Distance = 1,
}
impl Metric {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Displacement => "METRIC_DISPLACEMENT",
            Self::Distance => "METRIC_DISTANCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "METRIC_DISPLACEMENT" => Some(Self::Displacement),
            "METRIC_DISTANCE" => Some(Self::Distance),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Fire {
    /// fires on the first entry, then never until re-armed
    Once = 0,
    /// fires again after leaving by `hysteresis`
    Rearm = 1,
}
impl Fire {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Once => "FIRE_ONCE",
            Self::Rearm => "FIRE_REARM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FIRE_ONCE" => Some(Self::Once),
            "FIRE_REARM" => Some(Self::Rearm),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Action {
    /// active for `pulse_ms`
    Pulse = 0,
    /// active while engaged
    Level = 1,
}
impl Action {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pulse => "ACTION_PULSE",
            Self::Level => "ACTION_LEVEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTION_PULSE" => Some(Self::Pulse),
            "ACTION_LEVEL" => Some(Self::Level),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Origin {
    /// Displacement and distance are zero at the arm point — what a trial wants.
    Current = 0,
    /// Keep the device origin.
    Absolute = 1,
}
impl Origin {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Current => "ORIGIN_CURRENT",
            Self::Absolute => "ORIGIN_ABSOLUTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORIGIN_CURRENT" => Some(Self::Current),
            "ORIGIN_ABSOLUTE" => Some(Self::Absolute),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AnalogMode {
    Off = 0,
    /// displacement modulo `range_counts`, a sawtooth
    Wrap = 1,
    /// displacement clamped to \[lo, hi\]
    Clamp = 2,
    /// device velocity, counts/s, clamped to \[lo, hi\]
    Velocity = 3,
}
impl AnalogMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Off => "ANALOG_MODE_OFF",
            Self::Wrap => "ANALOG_MODE_WRAP",
            Self::Clamp => "ANALOG_MODE_CLAMP",
            Self::Velocity => "ANALOG_MODE_VELOCITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ANALOG_MODE_OFF" => Some(Self::Off),
            "ANALOG_MODE_WRAP" => Some(Self::Wrap),
            "ANALOG_MODE_CLAMP" => Some(Self::Clamp),
            "ANALOG_MODE_VELOCITY" => Some(Self::Velocity),
            _ => None,
        }
    }
}
