# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mousewheeld_client._proto.mousewheeld.v1 import device_pb2 as mousewheeld_dot_v1_dot_device__pb2
from mousewheeld_client._proto.mousewheeld.v1 import version_pb2 as mousewheeld_dot_v1_dot_version__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mousewheeld/v1/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceStub:
    """The board, and the wire to it.

    The first question anybody asks this daemon is whether a board is attached,
    and the second is which firmware is on it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadVersion = channel.unary_unary(
                '/mousewheeld.v1.Device/ReadVersion',
                request_serializer=mousewheeld_dot_v1_dot_device__pb2.ReadVersionRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_version__pb2.VersionReport.FromString,
                _registered_method=True)
        self.ReadDevice = channel.unary_unary(
                '/mousewheeld.v1.Device/ReadDevice',
                request_serializer=mousewheeld_dot_v1_dot_device__pb2.ReadDeviceRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.FromString,
                _registered_method=True)
        self.OpenLink = channel.unary_unary(
                '/mousewheeld.v1.Device/OpenLink',
                request_serializer=mousewheeld_dot_v1_dot_device__pb2.OpenLinkRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.FromString,
                _registered_method=True)
        self.ReadFirmware = channel.unary_unary(
                '/mousewheeld.v1.Device/ReadFirmware',
                request_serializer=mousewheeld_dot_v1_dot_device__pb2.ReadFirmwareRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_device__pb2.FirmwareVersions.FromString,
                _registered_method=True)
        self.ReadWireLog = channel.unary_unary(
                '/mousewheeld.v1.Device/ReadWireLog',
                request_serializer=mousewheeld_dot_v1_dot_device__pb2.ReadWireLogRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_device__pb2.WireLog.FromString,
                _registered_method=True)
        self.WatchWire = channel.unary_stream(
                '/mousewheeld.v1.Device/WatchWire',
                request_serializer=mousewheeld_dot_v1_dot_device__pb2.WatchWireRequest.SerializeToString,
                response_deserializer=mousewheeld_dot_v1_dot_device__pb2.WireLine.FromString,
                _registered_method=True)


class DeviceServicer:
    """The board, and the wire to it.

    The first question anybody asks this daemon is whether a board is attached,
    and the second is which firmware is on it.
    """

    def ReadVersion(self, request, context):
        """What this daemon is and what it speaks. Answers without a board.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDevice(self, request, context):
        """Whether a board is attached, which one, and how the link is holding up.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenLink(self, request, context):
        """Open the serial port named in the rig config and greet the board.

        Named `OpenLink` and not `Connect` because a generated client already has
        a `connect` — the one that opens the channel — and the two collide.

        Idempotent: connecting a connected daemon answers with what is already
        there. Refuses `no_device` when the port is not openable, and refuses a
        board whose protocol is below the floor **by name**, rather than speaking
        to it half-understood.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFirmware(self, request, context):
        """What the board is running, and what this daemon could flash onto it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadWireLog(self, request, context):
        """The recent wire, both directions, uninterpreted.

        A bounded ring. The conversation and the sample traffic are kept apart —
        at 500 Hz a shared ring evicts the `hello` handshake within seconds, which
        is exactly the part somebody reads a wire log to see.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchWire(self, request, context):
        """The same wire as it happens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadVersion,
                    request_deserializer=mousewheeld_dot_v1_dot_device__pb2.ReadVersionRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_version__pb2.VersionReport.SerializeToString,
            ),
            'ReadDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDevice,
                    request_deserializer=mousewheeld_dot_v1_dot_device__pb2.ReadDeviceRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.SerializeToString,
            ),
            'OpenLink': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenLink,
                    request_deserializer=mousewheeld_dot_v1_dot_device__pb2.OpenLinkRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.SerializeToString,
            ),
            'ReadFirmware': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFirmware,
                    request_deserializer=mousewheeld_dot_v1_dot_device__pb2.ReadFirmwareRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_device__pb2.FirmwareVersions.SerializeToString,
            ),
            'ReadWireLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadWireLog,
                    request_deserializer=mousewheeld_dot_v1_dot_device__pb2.ReadWireLogRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_device__pb2.WireLog.SerializeToString,
            ),
            'WatchWire': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchWire,
                    request_deserializer=mousewheeld_dot_v1_dot_device__pb2.WatchWireRequest.FromString,
                    response_serializer=mousewheeld_dot_v1_dot_device__pb2.WireLine.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mousewheeld.v1.Device', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mousewheeld.v1.Device', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Device:
    """The board, and the wire to it.

    The first question anybody asks this daemon is whether a board is attached,
    and the second is which firmware is on it.
    """

    @staticmethod
    def ReadVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Device/ReadVersion',
            mousewheeld_dot_v1_dot_device__pb2.ReadVersionRequest.SerializeToString,
            mousewheeld_dot_v1_dot_version__pb2.VersionReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Device/ReadDevice',
            mousewheeld_dot_v1_dot_device__pb2.ReadDeviceRequest.SerializeToString,
            mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Device/OpenLink',
            mousewheeld_dot_v1_dot_device__pb2.OpenLinkRequest.SerializeToString,
            mousewheeld_dot_v1_dot_device__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Device/ReadFirmware',
            mousewheeld_dot_v1_dot_device__pb2.ReadFirmwareRequest.SerializeToString,
            mousewheeld_dot_v1_dot_device__pb2.FirmwareVersions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadWireLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mousewheeld.v1.Device/ReadWireLog',
            mousewheeld_dot_v1_dot_device__pb2.ReadWireLogRequest.SerializeToString,
            mousewheeld_dot_v1_dot_device__pb2.WireLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchWire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mousewheeld.v1.Device/WatchWire',
            mousewheeld_dot_v1_dot_device__pb2.WatchWireRequest.SerializeToString,
            mousewheeld_dot_v1_dot_device__pb2.WireLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
