# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mousewheeld/v1/version.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mousewheeld/v1/version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmousewheeld/v1/version.proto\x12\x0emousewheeld.v1\"\x9c\x01\n\rVersionReport\x12\x0e\n\x06\x64\x61\x65mon\x18\x01 \x01(\t\x12\x0b\n\x03\x61pi\x18\x02 \x01(\r\x12H\n\x0f\x64\x65vice_protocol\x18\x03 \x01(\x0b\x32\x1e.mousewheeld.v1.DeviceProtocolR\x0f\x64\x65vice_protocol\x12$\n\rvinput_layout\x18\x04 \x01(\rR\rvinput_layout\"M\n\x0e\x44\x65viceProtocol\x12\x0e\n\x06speaks\x18\x01 \x01(\r\x12\r\n\x05\x66loor\x18\x02 \x01(\r\x12\x12\n\x05\x62oard\x18\x03 \x01(\rH\x00\x88\x01\x01\x42\x08\n\x06_boardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mousewheeld.v1.version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONREPORT']._serialized_start=49
  _globals['_VERSIONREPORT']._serialized_end=205
  _globals['_DEVICEPROTOCOL']._serialized_start=207
  _globals['_DEVICEPROTOCOL']._serialized_end=284
# @@protoc_insertion_point(module_scope)
